// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Role.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Msg_5fRole_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Msg_5fRole_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Msg_5fRole_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Msg_5fRole_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_5fRole_2eproto;
class RoleCreateAck;
struct RoleCreateAckDefaultTypeInternal;
extern RoleCreateAckDefaultTypeInternal _RoleCreateAck_default_instance_;
class RoleCreateReq;
struct RoleCreateReqDefaultTypeInternal;
extern RoleCreateReqDefaultTypeInternal _RoleCreateReq_default_instance_;
class RoleDeleteAck;
struct RoleDeleteAckDefaultTypeInternal;
extern RoleDeleteAckDefaultTypeInternal _RoleDeleteAck_default_instance_;
class RoleDeleteReq;
struct RoleDeleteReqDefaultTypeInternal;
extern RoleDeleteReqDefaultTypeInternal _RoleDeleteReq_default_instance_;
class RoleItem;
struct RoleItemDefaultTypeInternal;
extern RoleItemDefaultTypeInternal _RoleItem_default_instance_;
class RoleListAck;
struct RoleListAckDefaultTypeInternal;
extern RoleListAckDefaultTypeInternal _RoleListAck_default_instance_;
class RoleListReq;
struct RoleListReqDefaultTypeInternal;
extern RoleListReqDefaultTypeInternal _RoleListReq_default_instance_;
class RoleLoginReq;
struct RoleLoginReqDefaultTypeInternal;
extern RoleLoginReqDefaultTypeInternal _RoleLoginReq_default_instance_;
class RoleLogoutAck;
struct RoleLogoutAckDefaultTypeInternal;
extern RoleLogoutAckDefaultTypeInternal _RoleLogoutAck_default_instance_;
class RoleLogoutReq;
struct RoleLogoutReqDefaultTypeInternal;
extern RoleLogoutReqDefaultTypeInternal _RoleLogoutReq_default_instance_;
class RoleOtherLoginNty;
struct RoleOtherLoginNtyDefaultTypeInternal;
extern RoleOtherLoginNtyDefaultTypeInternal _RoleOtherLoginNty_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RoleCreateAck* Arena::CreateMaybeMessage<::RoleCreateAck>(Arena*);
template<> ::RoleCreateReq* Arena::CreateMaybeMessage<::RoleCreateReq>(Arena*);
template<> ::RoleDeleteAck* Arena::CreateMaybeMessage<::RoleDeleteAck>(Arena*);
template<> ::RoleDeleteReq* Arena::CreateMaybeMessage<::RoleDeleteReq>(Arena*);
template<> ::RoleItem* Arena::CreateMaybeMessage<::RoleItem>(Arena*);
template<> ::RoleListAck* Arena::CreateMaybeMessage<::RoleListAck>(Arena*);
template<> ::RoleListReq* Arena::CreateMaybeMessage<::RoleListReq>(Arena*);
template<> ::RoleLoginReq* Arena::CreateMaybeMessage<::RoleLoginReq>(Arena*);
template<> ::RoleLogoutAck* Arena::CreateMaybeMessage<::RoleLogoutAck>(Arena*);
template<> ::RoleLogoutReq* Arena::CreateMaybeMessage<::RoleLogoutReq>(Arena*);
template<> ::RoleOtherLoginNty* Arena::CreateMaybeMessage<::RoleOtherLoginNty>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class RoleItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleItem) */ {
 public:
  inline RoleItem() : RoleItem(nullptr) {}
  ~RoleItem() override;
  explicit PROTOBUF_CONSTEXPR RoleItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleItem(const RoleItem& from);
  RoleItem(RoleItem&& from) noexcept
    : RoleItem() {
    *this = ::std::move(from);
  }

  inline RoleItem& operator=(const RoleItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleItem& operator=(RoleItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleItem* internal_default_instance() {
    return reinterpret_cast<const RoleItem*>(
               &_RoleItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoleItem& a, RoleItem& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleItem& from) {
    RoleItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleItem";
  }
  protected:
  explicit RoleItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kRoleIDFieldNumber = 1,
    kCarrerFieldNumber = 3,
    kLevelFieldNumber = 4,
  };
  // string Name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 RoleID = 1;
  void clear_roleid();
  uint64_t roleid() const;
  void set_roleid(uint64_t value);
  private:
  uint64_t _internal_roleid() const;
  void _internal_set_roleid(uint64_t value);
  public:

  // int32 Carrer = 3;
  void clear_carrer();
  int32_t carrer() const;
  void set_carrer(int32_t value);
  private:
  int32_t _internal_carrer() const;
  void _internal_set_carrer(int32_t value);
  public:

  // int32 Level = 4;
  void clear_level();
  int32_t level() const;
  void set_level(int32_t value);
  private:
  int32_t _internal_level() const;
  void _internal_set_level(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint64_t roleid_;
    int32_t carrer_;
    int32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleListReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleListReq) */ {
 public:
  inline RoleListReq() : RoleListReq(nullptr) {}
  ~RoleListReq() override;
  explicit PROTOBUF_CONSTEXPR RoleListReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleListReq(const RoleListReq& from);
  RoleListReq(RoleListReq&& from) noexcept
    : RoleListReq() {
    *this = ::std::move(from);
  }

  inline RoleListReq& operator=(const RoleListReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleListReq& operator=(RoleListReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleListReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleListReq* internal_default_instance() {
    return reinterpret_cast<const RoleListReq*>(
               &_RoleListReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RoleListReq& a, RoleListReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleListReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleListReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleListReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleListReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleListReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleListReq& from) {
    RoleListReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleListReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleListReq";
  }
  protected:
  explicit RoleListReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIDFieldNumber = 1,
    kLoginCodeFieldNumber = 2,
    kServerIDFieldNumber = 3,
  };
  // uint64 AccountID = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // int32 LoginCode = 2;
  void clear_logincode();
  int32_t logincode() const;
  void set_logincode(int32_t value);
  private:
  int32_t _internal_logincode() const;
  void _internal_set_logincode(int32_t value);
  public:

  // uint32 ServerID = 3;
  void clear_serverid();
  uint32_t serverid() const;
  void set_serverid(uint32_t value);
  private:
  uint32_t _internal_serverid() const;
  void _internal_set_serverid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleListReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    int32_t logincode_;
    uint32_t serverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleListAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleListAck) */ {
 public:
  inline RoleListAck() : RoleListAck(nullptr) {}
  ~RoleListAck() override;
  explicit PROTOBUF_CONSTEXPR RoleListAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleListAck(const RoleListAck& from);
  RoleListAck(RoleListAck&& from) noexcept
    : RoleListAck() {
    *this = ::std::move(from);
  }

  inline RoleListAck& operator=(const RoleListAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleListAck& operator=(RoleListAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleListAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleListAck* internal_default_instance() {
    return reinterpret_cast<const RoleListAck*>(
               &_RoleListAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RoleListAck& a, RoleListAck& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleListAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleListAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleListAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleListAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleListAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleListAck& from) {
    RoleListAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleListAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleListAck";
  }
  protected:
  explicit RoleListAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoleListFieldNumber = 3,
    kAccountIDFieldNumber = 2,
    kRetCodeFieldNumber = 1,
  };
  // repeated .RoleItem RoleList = 3;
  int rolelist_size() const;
  private:
  int _internal_rolelist_size() const;
  public:
  void clear_rolelist();
  ::RoleItem* mutable_rolelist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RoleItem >*
      mutable_rolelist();
  private:
  const ::RoleItem& _internal_rolelist(int index) const;
  ::RoleItem* _internal_add_rolelist();
  public:
  const ::RoleItem& rolelist(int index) const;
  ::RoleItem* add_rolelist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RoleItem >&
      rolelist() const;

  // uint64 AccountID = 2;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint32 RetCode = 1;
  void clear_retcode();
  uint32_t retcode() const;
  void set_retcode(uint32_t value);
  private:
  uint32_t _internal_retcode() const;
  void _internal_set_retcode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleListAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RoleItem > rolelist_;
    uint64_t accountid_;
    uint32_t retcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleCreateReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleCreateReq) */ {
 public:
  inline RoleCreateReq() : RoleCreateReq(nullptr) {}
  ~RoleCreateReq() override;
  explicit PROTOBUF_CONSTEXPR RoleCreateReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleCreateReq(const RoleCreateReq& from);
  RoleCreateReq(RoleCreateReq&& from) noexcept
    : RoleCreateReq() {
    *this = ::std::move(from);
  }

  inline RoleCreateReq& operator=(const RoleCreateReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleCreateReq& operator=(RoleCreateReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleCreateReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleCreateReq* internal_default_instance() {
    return reinterpret_cast<const RoleCreateReq*>(
               &_RoleCreateReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RoleCreateReq& a, RoleCreateReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleCreateReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleCreateReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleCreateReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleCreateReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleCreateReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleCreateReq& from) {
    RoleCreateReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleCreateReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleCreateReq";
  }
  protected:
  explicit RoleCreateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kAccountIDFieldNumber = 1,
    kCarrerFieldNumber = 3,
    kChannelFieldNumber = 4,
  };
  // string Name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 AccountID = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // int32 Carrer = 3;
  void clear_carrer();
  int32_t carrer() const;
  void set_carrer(int32_t value);
  private:
  int32_t _internal_carrer() const;
  void _internal_set_carrer(int32_t value);
  public:

  // int32 Channel = 4;
  void clear_channel();
  int32_t channel() const;
  void set_channel(int32_t value);
  private:
  int32_t _internal_channel() const;
  void _internal_set_channel(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleCreateReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint64_t accountid_;
    int32_t carrer_;
    int32_t channel_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleCreateAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleCreateAck) */ {
 public:
  inline RoleCreateAck() : RoleCreateAck(nullptr) {}
  ~RoleCreateAck() override;
  explicit PROTOBUF_CONSTEXPR RoleCreateAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleCreateAck(const RoleCreateAck& from);
  RoleCreateAck(RoleCreateAck&& from) noexcept
    : RoleCreateAck() {
    *this = ::std::move(from);
  }

  inline RoleCreateAck& operator=(const RoleCreateAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleCreateAck& operator=(RoleCreateAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleCreateAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleCreateAck* internal_default_instance() {
    return reinterpret_cast<const RoleCreateAck*>(
               &_RoleCreateAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RoleCreateAck& a, RoleCreateAck& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleCreateAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleCreateAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleCreateAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleCreateAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleCreateAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleCreateAck& from) {
    RoleCreateAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleCreateAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleCreateAck";
  }
  protected:
  explicit RoleCreateAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 4,
    kAccountIDFieldNumber = 2,
    kRoleIDFieldNumber = 3,
    kRetCodeFieldNumber = 1,
    kCarrerFieldNumber = 5,
  };
  // string Name = 4;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 AccountID = 2;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint64 RoleID = 3;
  void clear_roleid();
  uint64_t roleid() const;
  void set_roleid(uint64_t value);
  private:
  uint64_t _internal_roleid() const;
  void _internal_set_roleid(uint64_t value);
  public:

  // uint32 RetCode = 1;
  void clear_retcode();
  uint32_t retcode() const;
  void set_retcode(uint32_t value);
  private:
  uint32_t _internal_retcode() const;
  void _internal_set_retcode(uint32_t value);
  public:

  // int32 Carrer = 5;
  void clear_carrer();
  int32_t carrer() const;
  void set_carrer(int32_t value);
  private:
  int32_t _internal_carrer() const;
  void _internal_set_carrer(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleCreateAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint64_t accountid_;
    uint64_t roleid_;
    uint32_t retcode_;
    int32_t carrer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleDeleteReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleDeleteReq) */ {
 public:
  inline RoleDeleteReq() : RoleDeleteReq(nullptr) {}
  ~RoleDeleteReq() override;
  explicit PROTOBUF_CONSTEXPR RoleDeleteReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleDeleteReq(const RoleDeleteReq& from);
  RoleDeleteReq(RoleDeleteReq&& from) noexcept
    : RoleDeleteReq() {
    *this = ::std::move(from);
  }

  inline RoleDeleteReq& operator=(const RoleDeleteReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleDeleteReq& operator=(RoleDeleteReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleDeleteReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleDeleteReq* internal_default_instance() {
    return reinterpret_cast<const RoleDeleteReq*>(
               &_RoleDeleteReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(RoleDeleteReq& a, RoleDeleteReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleDeleteReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleDeleteReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleDeleteReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleDeleteReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleDeleteReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleDeleteReq& from) {
    RoleDeleteReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleDeleteReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleDeleteReq";
  }
  protected:
  explicit RoleDeleteReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIDFieldNumber = 1,
    kRoleIDFieldNumber = 2,
  };
  // uint64 AccountID = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint64 RoleID = 2;
  void clear_roleid();
  uint64_t roleid() const;
  void set_roleid(uint64_t value);
  private:
  uint64_t _internal_roleid() const;
  void _internal_set_roleid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleDeleteReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    uint64_t roleid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleDeleteAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleDeleteAck) */ {
 public:
  inline RoleDeleteAck() : RoleDeleteAck(nullptr) {}
  ~RoleDeleteAck() override;
  explicit PROTOBUF_CONSTEXPR RoleDeleteAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleDeleteAck(const RoleDeleteAck& from);
  RoleDeleteAck(RoleDeleteAck&& from) noexcept
    : RoleDeleteAck() {
    *this = ::std::move(from);
  }

  inline RoleDeleteAck& operator=(const RoleDeleteAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleDeleteAck& operator=(RoleDeleteAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleDeleteAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleDeleteAck* internal_default_instance() {
    return reinterpret_cast<const RoleDeleteAck*>(
               &_RoleDeleteAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(RoleDeleteAck& a, RoleDeleteAck& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleDeleteAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleDeleteAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleDeleteAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleDeleteAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleDeleteAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleDeleteAck& from) {
    RoleDeleteAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleDeleteAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleDeleteAck";
  }
  protected:
  explicit RoleDeleteAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRetCodeFieldNumber = 1,
  };
  // uint32 RetCode = 1;
  void clear_retcode();
  uint32_t retcode() const;
  void set_retcode(uint32_t value);
  private:
  uint32_t _internal_retcode() const;
  void _internal_set_retcode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleDeleteAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t retcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleLoginReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleLoginReq) */ {
 public:
  inline RoleLoginReq() : RoleLoginReq(nullptr) {}
  ~RoleLoginReq() override;
  explicit PROTOBUF_CONSTEXPR RoleLoginReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleLoginReq(const RoleLoginReq& from);
  RoleLoginReq(RoleLoginReq&& from) noexcept
    : RoleLoginReq() {
    *this = ::std::move(from);
  }

  inline RoleLoginReq& operator=(const RoleLoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleLoginReq& operator=(RoleLoginReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleLoginReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleLoginReq* internal_default_instance() {
    return reinterpret_cast<const RoleLoginReq*>(
               &_RoleLoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(RoleLoginReq& a, RoleLoginReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleLoginReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleLoginReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleLoginReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleLoginReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleLoginReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleLoginReq& from) {
    RoleLoginReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleLoginReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleLoginReq";
  }
  protected:
  explicit RoleLoginReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIDFieldNumber = 1,
    kRoleIDFieldNumber = 2,
    kLangIDFieldNumber = 3,
  };
  // uint64 AccountID = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint64 RoleID = 2;
  void clear_roleid();
  uint64_t roleid() const;
  void set_roleid(uint64_t value);
  private:
  uint64_t _internal_roleid() const;
  void _internal_set_roleid(uint64_t value);
  public:

  // int32 LangID = 3;
  void clear_langid();
  int32_t langid() const;
  void set_langid(int32_t value);
  private:
  int32_t _internal_langid() const;
  void _internal_set_langid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleLoginReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    uint64_t roleid_;
    int32_t langid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleLogoutReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleLogoutReq) */ {
 public:
  inline RoleLogoutReq() : RoleLogoutReq(nullptr) {}
  ~RoleLogoutReq() override;
  explicit PROTOBUF_CONSTEXPR RoleLogoutReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleLogoutReq(const RoleLogoutReq& from);
  RoleLogoutReq(RoleLogoutReq&& from) noexcept
    : RoleLogoutReq() {
    *this = ::std::move(from);
  }

  inline RoleLogoutReq& operator=(const RoleLogoutReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleLogoutReq& operator=(RoleLogoutReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleLogoutReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleLogoutReq* internal_default_instance() {
    return reinterpret_cast<const RoleLogoutReq*>(
               &_RoleLogoutReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(RoleLogoutReq& a, RoleLogoutReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleLogoutReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleLogoutReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleLogoutReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleLogoutReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleLogoutReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleLogoutReq& from) {
    RoleLogoutReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleLogoutReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleLogoutReq";
  }
  protected:
  explicit RoleLogoutReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIDFieldNumber = 1,
  };
  // uint64 AccountID = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleLogoutReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleLogoutAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleLogoutAck) */ {
 public:
  inline RoleLogoutAck() : RoleLogoutAck(nullptr) {}
  ~RoleLogoutAck() override;
  explicit PROTOBUF_CONSTEXPR RoleLogoutAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleLogoutAck(const RoleLogoutAck& from);
  RoleLogoutAck(RoleLogoutAck&& from) noexcept
    : RoleLogoutAck() {
    *this = ::std::move(from);
  }

  inline RoleLogoutAck& operator=(const RoleLogoutAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleLogoutAck& operator=(RoleLogoutAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleLogoutAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleLogoutAck* internal_default_instance() {
    return reinterpret_cast<const RoleLogoutAck*>(
               &_RoleLogoutAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(RoleLogoutAck& a, RoleLogoutAck& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleLogoutAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleLogoutAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleLogoutAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleLogoutAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleLogoutAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleLogoutAck& from) {
    RoleLogoutAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleLogoutAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleLogoutAck";
  }
  protected:
  explicit RoleLogoutAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRetCodeFieldNumber = 1,
  };
  // uint32 RetCode = 1;
  void clear_retcode();
  uint32_t retcode() const;
  void set_retcode(uint32_t value);
  private:
  uint32_t _internal_retcode() const;
  void _internal_set_retcode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleLogoutAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t retcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// -------------------------------------------------------------------

class RoleOtherLoginNty final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoleOtherLoginNty) */ {
 public:
  inline RoleOtherLoginNty() : RoleOtherLoginNty(nullptr) {}
  ~RoleOtherLoginNty() override;
  explicit PROTOBUF_CONSTEXPR RoleOtherLoginNty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoleOtherLoginNty(const RoleOtherLoginNty& from);
  RoleOtherLoginNty(RoleOtherLoginNty&& from) noexcept
    : RoleOtherLoginNty() {
    *this = ::std::move(from);
  }

  inline RoleOtherLoginNty& operator=(const RoleOtherLoginNty& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoleOtherLoginNty& operator=(RoleOtherLoginNty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoleOtherLoginNty& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoleOtherLoginNty* internal_default_instance() {
    return reinterpret_cast<const RoleOtherLoginNty*>(
               &_RoleOtherLoginNty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(RoleOtherLoginNty& a, RoleOtherLoginNty& b) {
    a.Swap(&b);
  }
  inline void Swap(RoleOtherLoginNty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoleOtherLoginNty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoleOtherLoginNty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoleOtherLoginNty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoleOtherLoginNty& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoleOtherLoginNty& from) {
    RoleOtherLoginNty::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoleOtherLoginNty* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoleOtherLoginNty";
  }
  protected:
  explicit RoleOtherLoginNty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRetCodeFieldNumber = 1,
  };
  // uint32 RetCode = 1;
  void clear_retcode();
  uint32_t retcode() const;
  void set_retcode(uint32_t value);
  private:
  uint32_t _internal_retcode() const;
  void _internal_set_retcode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RoleOtherLoginNty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t retcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Msg_5fRole_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoleItem

// uint64 RoleID = 1;
inline void RoleItem::clear_roleid() {
  _impl_.roleid_ = uint64_t{0u};
}
inline uint64_t RoleItem::_internal_roleid() const {
  return _impl_.roleid_;
}
inline uint64_t RoleItem::roleid() const {
  // @@protoc_insertion_point(field_get:RoleItem.RoleID)
  return _internal_roleid();
}
inline void RoleItem::_internal_set_roleid(uint64_t value) {
  
  _impl_.roleid_ = value;
}
inline void RoleItem::set_roleid(uint64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:RoleItem.RoleID)
}

// string Name = 2;
inline void RoleItem::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RoleItem::name() const {
  // @@protoc_insertion_point(field_get:RoleItem.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoleItem::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RoleItem.Name)
}
inline std::string* RoleItem::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:RoleItem.Name)
  return _s;
}
inline const std::string& RoleItem::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RoleItem::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RoleItem::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RoleItem::release_name() {
  // @@protoc_insertion_point(field_release:RoleItem.Name)
  return _impl_.name_.Release();
}
inline void RoleItem::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RoleItem.Name)
}

// int32 Carrer = 3;
inline void RoleItem::clear_carrer() {
  _impl_.carrer_ = 0;
}
inline int32_t RoleItem::_internal_carrer() const {
  return _impl_.carrer_;
}
inline int32_t RoleItem::carrer() const {
  // @@protoc_insertion_point(field_get:RoleItem.Carrer)
  return _internal_carrer();
}
inline void RoleItem::_internal_set_carrer(int32_t value) {
  
  _impl_.carrer_ = value;
}
inline void RoleItem::set_carrer(int32_t value) {
  _internal_set_carrer(value);
  // @@protoc_insertion_point(field_set:RoleItem.Carrer)
}

// int32 Level = 4;
inline void RoleItem::clear_level() {
  _impl_.level_ = 0;
}
inline int32_t RoleItem::_internal_level() const {
  return _impl_.level_;
}
inline int32_t RoleItem::level() const {
  // @@protoc_insertion_point(field_get:RoleItem.Level)
  return _internal_level();
}
inline void RoleItem::_internal_set_level(int32_t value) {
  
  _impl_.level_ = value;
}
inline void RoleItem::set_level(int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:RoleItem.Level)
}

// -------------------------------------------------------------------

// RoleListReq

// uint64 AccountID = 1;
inline void RoleListReq::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleListReq::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleListReq::accountid() const {
  // @@protoc_insertion_point(field_get:RoleListReq.AccountID)
  return _internal_accountid();
}
inline void RoleListReq::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleListReq::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleListReq.AccountID)
}

// int32 LoginCode = 2;
inline void RoleListReq::clear_logincode() {
  _impl_.logincode_ = 0;
}
inline int32_t RoleListReq::_internal_logincode() const {
  return _impl_.logincode_;
}
inline int32_t RoleListReq::logincode() const {
  // @@protoc_insertion_point(field_get:RoleListReq.LoginCode)
  return _internal_logincode();
}
inline void RoleListReq::_internal_set_logincode(int32_t value) {
  
  _impl_.logincode_ = value;
}
inline void RoleListReq::set_logincode(int32_t value) {
  _internal_set_logincode(value);
  // @@protoc_insertion_point(field_set:RoleListReq.LoginCode)
}

// uint32 ServerID = 3;
inline void RoleListReq::clear_serverid() {
  _impl_.serverid_ = 0u;
}
inline uint32_t RoleListReq::_internal_serverid() const {
  return _impl_.serverid_;
}
inline uint32_t RoleListReq::serverid() const {
  // @@protoc_insertion_point(field_get:RoleListReq.ServerID)
  return _internal_serverid();
}
inline void RoleListReq::_internal_set_serverid(uint32_t value) {
  
  _impl_.serverid_ = value;
}
inline void RoleListReq::set_serverid(uint32_t value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:RoleListReq.ServerID)
}

// -------------------------------------------------------------------

// RoleListAck

// uint32 RetCode = 1;
inline void RoleListAck::clear_retcode() {
  _impl_.retcode_ = 0u;
}
inline uint32_t RoleListAck::_internal_retcode() const {
  return _impl_.retcode_;
}
inline uint32_t RoleListAck::retcode() const {
  // @@protoc_insertion_point(field_get:RoleListAck.RetCode)
  return _internal_retcode();
}
inline void RoleListAck::_internal_set_retcode(uint32_t value) {
  
  _impl_.retcode_ = value;
}
inline void RoleListAck::set_retcode(uint32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:RoleListAck.RetCode)
}

// uint64 AccountID = 2;
inline void RoleListAck::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleListAck::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleListAck::accountid() const {
  // @@protoc_insertion_point(field_get:RoleListAck.AccountID)
  return _internal_accountid();
}
inline void RoleListAck::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleListAck::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleListAck.AccountID)
}

// repeated .RoleItem RoleList = 3;
inline int RoleListAck::_internal_rolelist_size() const {
  return _impl_.rolelist_.size();
}
inline int RoleListAck::rolelist_size() const {
  return _internal_rolelist_size();
}
inline void RoleListAck::clear_rolelist() {
  _impl_.rolelist_.Clear();
}
inline ::RoleItem* RoleListAck::mutable_rolelist(int index) {
  // @@protoc_insertion_point(field_mutable:RoleListAck.RoleList)
  return _impl_.rolelist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RoleItem >*
RoleListAck::mutable_rolelist() {
  // @@protoc_insertion_point(field_mutable_list:RoleListAck.RoleList)
  return &_impl_.rolelist_;
}
inline const ::RoleItem& RoleListAck::_internal_rolelist(int index) const {
  return _impl_.rolelist_.Get(index);
}
inline const ::RoleItem& RoleListAck::rolelist(int index) const {
  // @@protoc_insertion_point(field_get:RoleListAck.RoleList)
  return _internal_rolelist(index);
}
inline ::RoleItem* RoleListAck::_internal_add_rolelist() {
  return _impl_.rolelist_.Add();
}
inline ::RoleItem* RoleListAck::add_rolelist() {
  ::RoleItem* _add = _internal_add_rolelist();
  // @@protoc_insertion_point(field_add:RoleListAck.RoleList)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RoleItem >&
RoleListAck::rolelist() const {
  // @@protoc_insertion_point(field_list:RoleListAck.RoleList)
  return _impl_.rolelist_;
}

// -------------------------------------------------------------------

// RoleCreateReq

// uint64 AccountID = 1;
inline void RoleCreateReq::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleCreateReq::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleCreateReq::accountid() const {
  // @@protoc_insertion_point(field_get:RoleCreateReq.AccountID)
  return _internal_accountid();
}
inline void RoleCreateReq::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleCreateReq::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleCreateReq.AccountID)
}

// string Name = 2;
inline void RoleCreateReq::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RoleCreateReq::name() const {
  // @@protoc_insertion_point(field_get:RoleCreateReq.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoleCreateReq::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RoleCreateReq.Name)
}
inline std::string* RoleCreateReq::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:RoleCreateReq.Name)
  return _s;
}
inline const std::string& RoleCreateReq::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RoleCreateReq::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RoleCreateReq::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RoleCreateReq::release_name() {
  // @@protoc_insertion_point(field_release:RoleCreateReq.Name)
  return _impl_.name_.Release();
}
inline void RoleCreateReq::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RoleCreateReq.Name)
}

// int32 Carrer = 3;
inline void RoleCreateReq::clear_carrer() {
  _impl_.carrer_ = 0;
}
inline int32_t RoleCreateReq::_internal_carrer() const {
  return _impl_.carrer_;
}
inline int32_t RoleCreateReq::carrer() const {
  // @@protoc_insertion_point(field_get:RoleCreateReq.Carrer)
  return _internal_carrer();
}
inline void RoleCreateReq::_internal_set_carrer(int32_t value) {
  
  _impl_.carrer_ = value;
}
inline void RoleCreateReq::set_carrer(int32_t value) {
  _internal_set_carrer(value);
  // @@protoc_insertion_point(field_set:RoleCreateReq.Carrer)
}

// int32 Channel = 4;
inline void RoleCreateReq::clear_channel() {
  _impl_.channel_ = 0;
}
inline int32_t RoleCreateReq::_internal_channel() const {
  return _impl_.channel_;
}
inline int32_t RoleCreateReq::channel() const {
  // @@protoc_insertion_point(field_get:RoleCreateReq.Channel)
  return _internal_channel();
}
inline void RoleCreateReq::_internal_set_channel(int32_t value) {
  
  _impl_.channel_ = value;
}
inline void RoleCreateReq::set_channel(int32_t value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:RoleCreateReq.Channel)
}

// -------------------------------------------------------------------

// RoleCreateAck

// uint32 RetCode = 1;
inline void RoleCreateAck::clear_retcode() {
  _impl_.retcode_ = 0u;
}
inline uint32_t RoleCreateAck::_internal_retcode() const {
  return _impl_.retcode_;
}
inline uint32_t RoleCreateAck::retcode() const {
  // @@protoc_insertion_point(field_get:RoleCreateAck.RetCode)
  return _internal_retcode();
}
inline void RoleCreateAck::_internal_set_retcode(uint32_t value) {
  
  _impl_.retcode_ = value;
}
inline void RoleCreateAck::set_retcode(uint32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:RoleCreateAck.RetCode)
}

// uint64 AccountID = 2;
inline void RoleCreateAck::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleCreateAck::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleCreateAck::accountid() const {
  // @@protoc_insertion_point(field_get:RoleCreateAck.AccountID)
  return _internal_accountid();
}
inline void RoleCreateAck::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleCreateAck::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleCreateAck.AccountID)
}

// uint64 RoleID = 3;
inline void RoleCreateAck::clear_roleid() {
  _impl_.roleid_ = uint64_t{0u};
}
inline uint64_t RoleCreateAck::_internal_roleid() const {
  return _impl_.roleid_;
}
inline uint64_t RoleCreateAck::roleid() const {
  // @@protoc_insertion_point(field_get:RoleCreateAck.RoleID)
  return _internal_roleid();
}
inline void RoleCreateAck::_internal_set_roleid(uint64_t value) {
  
  _impl_.roleid_ = value;
}
inline void RoleCreateAck::set_roleid(uint64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:RoleCreateAck.RoleID)
}

// string Name = 4;
inline void RoleCreateAck::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RoleCreateAck::name() const {
  // @@protoc_insertion_point(field_get:RoleCreateAck.Name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoleCreateAck::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RoleCreateAck.Name)
}
inline std::string* RoleCreateAck::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:RoleCreateAck.Name)
  return _s;
}
inline const std::string& RoleCreateAck::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RoleCreateAck::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RoleCreateAck::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RoleCreateAck::release_name() {
  // @@protoc_insertion_point(field_release:RoleCreateAck.Name)
  return _impl_.name_.Release();
}
inline void RoleCreateAck::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RoleCreateAck.Name)
}

// int32 Carrer = 5;
inline void RoleCreateAck::clear_carrer() {
  _impl_.carrer_ = 0;
}
inline int32_t RoleCreateAck::_internal_carrer() const {
  return _impl_.carrer_;
}
inline int32_t RoleCreateAck::carrer() const {
  // @@protoc_insertion_point(field_get:RoleCreateAck.Carrer)
  return _internal_carrer();
}
inline void RoleCreateAck::_internal_set_carrer(int32_t value) {
  
  _impl_.carrer_ = value;
}
inline void RoleCreateAck::set_carrer(int32_t value) {
  _internal_set_carrer(value);
  // @@protoc_insertion_point(field_set:RoleCreateAck.Carrer)
}

// -------------------------------------------------------------------

// RoleDeleteReq

// uint64 AccountID = 1;
inline void RoleDeleteReq::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleDeleteReq::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleDeleteReq::accountid() const {
  // @@protoc_insertion_point(field_get:RoleDeleteReq.AccountID)
  return _internal_accountid();
}
inline void RoleDeleteReq::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleDeleteReq::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleDeleteReq.AccountID)
}

// uint64 RoleID = 2;
inline void RoleDeleteReq::clear_roleid() {
  _impl_.roleid_ = uint64_t{0u};
}
inline uint64_t RoleDeleteReq::_internal_roleid() const {
  return _impl_.roleid_;
}
inline uint64_t RoleDeleteReq::roleid() const {
  // @@protoc_insertion_point(field_get:RoleDeleteReq.RoleID)
  return _internal_roleid();
}
inline void RoleDeleteReq::_internal_set_roleid(uint64_t value) {
  
  _impl_.roleid_ = value;
}
inline void RoleDeleteReq::set_roleid(uint64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:RoleDeleteReq.RoleID)
}

// -------------------------------------------------------------------

// RoleDeleteAck

// uint32 RetCode = 1;
inline void RoleDeleteAck::clear_retcode() {
  _impl_.retcode_ = 0u;
}
inline uint32_t RoleDeleteAck::_internal_retcode() const {
  return _impl_.retcode_;
}
inline uint32_t RoleDeleteAck::retcode() const {
  // @@protoc_insertion_point(field_get:RoleDeleteAck.RetCode)
  return _internal_retcode();
}
inline void RoleDeleteAck::_internal_set_retcode(uint32_t value) {
  
  _impl_.retcode_ = value;
}
inline void RoleDeleteAck::set_retcode(uint32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:RoleDeleteAck.RetCode)
}

// -------------------------------------------------------------------

// RoleLoginReq

// uint64 AccountID = 1;
inline void RoleLoginReq::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleLoginReq::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleLoginReq::accountid() const {
  // @@protoc_insertion_point(field_get:RoleLoginReq.AccountID)
  return _internal_accountid();
}
inline void RoleLoginReq::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleLoginReq::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleLoginReq.AccountID)
}

// uint64 RoleID = 2;
inline void RoleLoginReq::clear_roleid() {
  _impl_.roleid_ = uint64_t{0u};
}
inline uint64_t RoleLoginReq::_internal_roleid() const {
  return _impl_.roleid_;
}
inline uint64_t RoleLoginReq::roleid() const {
  // @@protoc_insertion_point(field_get:RoleLoginReq.RoleID)
  return _internal_roleid();
}
inline void RoleLoginReq::_internal_set_roleid(uint64_t value) {
  
  _impl_.roleid_ = value;
}
inline void RoleLoginReq::set_roleid(uint64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:RoleLoginReq.RoleID)
}

// int32 LangID = 3;
inline void RoleLoginReq::clear_langid() {
  _impl_.langid_ = 0;
}
inline int32_t RoleLoginReq::_internal_langid() const {
  return _impl_.langid_;
}
inline int32_t RoleLoginReq::langid() const {
  // @@protoc_insertion_point(field_get:RoleLoginReq.LangID)
  return _internal_langid();
}
inline void RoleLoginReq::_internal_set_langid(int32_t value) {
  
  _impl_.langid_ = value;
}
inline void RoleLoginReq::set_langid(int32_t value) {
  _internal_set_langid(value);
  // @@protoc_insertion_point(field_set:RoleLoginReq.LangID)
}

// -------------------------------------------------------------------

// RoleLogoutReq

// uint64 AccountID = 1;
inline void RoleLogoutReq::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t RoleLogoutReq::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t RoleLogoutReq::accountid() const {
  // @@protoc_insertion_point(field_get:RoleLogoutReq.AccountID)
  return _internal_accountid();
}
inline void RoleLogoutReq::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void RoleLogoutReq::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:RoleLogoutReq.AccountID)
}

// -------------------------------------------------------------------

// RoleLogoutAck

// uint32 RetCode = 1;
inline void RoleLogoutAck::clear_retcode() {
  _impl_.retcode_ = 0u;
}
inline uint32_t RoleLogoutAck::_internal_retcode() const {
  return _impl_.retcode_;
}
inline uint32_t RoleLogoutAck::retcode() const {
  // @@protoc_insertion_point(field_get:RoleLogoutAck.RetCode)
  return _internal_retcode();
}
inline void RoleLogoutAck::_internal_set_retcode(uint32_t value) {
  
  _impl_.retcode_ = value;
}
inline void RoleLogoutAck::set_retcode(uint32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:RoleLogoutAck.RetCode)
}

// -------------------------------------------------------------------

// RoleOtherLoginNty

// uint32 RetCode = 1;
inline void RoleOtherLoginNty::clear_retcode() {
  _impl_.retcode_ = 0u;
}
inline uint32_t RoleOtherLoginNty::_internal_retcode() const {
  return _impl_.retcode_;
}
inline uint32_t RoleOtherLoginNty::retcode() const {
  // @@protoc_insertion_point(field_get:RoleOtherLoginNty.RetCode)
  return _internal_retcode();
}
inline void RoleOtherLoginNty::_internal_set_retcode(uint32_t value) {
  
  _impl_.retcode_ = value;
}
inline void RoleOtherLoginNty::set_retcode(uint32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:RoleOtherLoginNty.RetCode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Msg_5fRole_2eproto
