/* NOTE: original file backed up at /tmp/chinese_backups/Server___Src___StaticData___StaticStruct.h */
#ifndef __STATIC_STRUCT_H__
#define __STATIC_STRUCT_H__
#include "../Message/Game_Define.pb.h"
struct  StConstantValue
{
	StConstantValue() {}

	UINT32 xxxx;
};


struct StCopyInfo
{
	StCopyInfo()
	{

	}

	UINT32 dwCopyID;
	UINT32 dwCopyType;     //[TRANSLATED][TRANSLATED]type
	UINT32 dwCostActID;    //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
	UINT32 dwCostActNum;   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]count
	UINT32 dwGetMoneyID;   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
	UINT32 dwGetMoneyRatio;//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32 dwGetExpRation; //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32 dwAwardID;      //[TRANSLATED][TRANSLATED]ID
	UINT32 dwFirstAwardID; //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
	UINT32 dwBattleTimes;  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

	std::string strXml;
};


struct StLocalString
{
	StLocalString()
	{

	}
	UINT32  dwID;
	std::string Language[MAX_LANGUAGE_NUM];
};

struct StActorInfo
{
	StActorInfo()
	{
		dwID        = 0;
		fRadius     = 0;
		fDefSpeed   = 0;
		InitLevel   = 0;
		dwType      = 0;
		AiID        = 0;
	}
	UINT32  dwID;
	FLOAT   fRadius;
	FLOAT	fDefSpeed;
	INT32   dwType;
	INT32   InitLevel; //[TRANSLATED][TRANSLATED]Level
	INT32   AiID;
	INT32   Propertys[PROPERTY_NUM];

	std::string strName;
};

struct StActorSkillInfo
{
	StActorSkillInfo()
	{
	}
	UINT32  dwActorID = 0;
	INT32   NormalID = 0;
	INT32   Specials[5] = { 0 };
};

struct StChargeInfo
{
	StChargeInfo()
	{
	}
	UINT32  dwProductID = 0;
};

struct StCarrerInfo
{
	StCarrerInfo()
	{
		dwID		= 0;
		dwActorID	= 0;
		dwBornCity	= 0;
		strName		= "";
	}
	UINT32  dwID;
	UINT32  dwActorID;
	UINT32  dwBornCity;

	std::string strName;
};

struct StLevelInfo
{
	StLevelInfo()
	{
		dwLevel = 0;
		dwFightValue = 0;
		dwNeedExp = 0;
		dwCarrerID = 0;
	}

	UINT32 dwCarrerID;
	UINT32 dwLevel;
	UINT32 dwNeedExp;
	INT32  Propertys[PROPERTY_NUM];
	UINT32 dwFightValue;
};

struct StActionInfo
{
	StActionInfo()
	{
		dwActionID = 0;		// [TRANSLATED][TRANSLATED][TRANSLATED]ID
		UnitTime = 0;		//[TRANSLATED][TRANSLATED]1[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED])
		dwMax = 0;			//[TRANSLATED][TRANSLATED][TRANSLATED]
	}

	UINT32 dwActionID;	// [TRANSLATED][TRANSLATED][TRANSLATED]ID
	INT32 UnitTime;		//[TRANSLATED][TRANSLATED]1[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED])
	UINT32 dwMax;		//[TRANSLATED][TRANSLATED][TRANSLATED]
};


struct  StItemData
{
	UINT32 dwItemID;
	UINT32 dwItemNum;
};


//[TRANSLATED][TRANSLATED][TRANSLATED]
struct StDropItem
{
	UINT32 dwItemID;		//[TRANSLATED][TRANSLATED]ID
	UINT32 dwItemNum[2];	//[TRANSLATED][TRANSLATED]count
	UINT32 dwRatio;			//[TRANSLATED][TRANSLATED]range
};

//[TRANSLATED][TRANSLATED][TRANSLATED]
struct StAwardItem
{
	INT32 dwAwardID;					//[TRANSLATED][TRANSLATED]ID
	INT32 dwRatioCount;					//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL bDistinct;						//whether[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	INT32 nCarrer;						//[TRANSLATED][TRANSLATED]
	std::vector<StDropItem> FixItems;	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	std::vector<StDropItem>  RatioItems;//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
};

struct StItemInfo
{
	UINT32 dwItemID;	//[TRANSLATED][TRANSLATED]ID
	EItemType eItemType;//[TRANSLATED][TRANSLATED]type
	UINT32 dwBagType;	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]type
	UINT32 Quality;		//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32 SellID;		//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
	INT32  SellPrice;	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32 UseType;		//[TRANSLATED][TRANSLATED]type
	UINT32 CarrerID;	//[TRANSLATED][TRANSLATED]
	INT64  StackMax;	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	INT32  Data1;		//params1
	INT32  Data2;		//params2
};


struct StFuncInfo
{
	UINT32 dwFuncID;	//! [TRANSLATED][TRANSLATED]ID
	INT32 OpenLevel;	//! [TRANSLATED][TRANSLATED]Level
	INT32 VipLevel;		//! VIP[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]Level
	INT32 Logic;		//! [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] 1:[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]; 2:[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]; 3: [TRANSLATED][TRANSLATED]VIP[TRANSLATED][TRANSLATED]; 4:[TRANSLATED][TRANSLATED]Level[TRANSLATED][TRANSLATED]
};


struct StFuncVipInfo
{
	UINT32 dwFuncID;				//! [TRANSLATED][TRANSLATED]ID
	INT32  VipValue[MAX_VIP_LEVEL];	//! [TRANSLATED][TRANSLATED]VIP[TRANSLATED][TRANSLATED]
};


struct StEquipInfo
{
	UINT32 dwEquipID;		//! ID
	UINT32 dwSuitID;
	UINT32 dwPos;
};

struct StGemInfo
{
	UINT32 dwGemID;		//! ID
	UINT32 dwPos;
};

struct StPetInfo
{
	UINT32 dwPetID;		//! ID
	UINT32 dwActorID;
};

struct StPartnerInfo
{
	UINT32  dwPartnerID;		//! ID
	UINT32  dwActorID;
};


struct StMountInfo
{
	UINT32  dwMountID;		//! ID
	UINT32  dwActorID;
};

struct StTaskInfo
{
	UINT32 TaskID;		//! [TRANSLATED][TRANSLATED]ID
	UINT32 PrevTaskID;  //! [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
	UINT32 TaskType;	//! [TRANSLATED][TRANSLATED]type([TRANSLATED][TRANSLATED]， [TRANSLATED][TRANSLATED]， [TRANSLATED][TRANSLATED]，guild)
	UINT32 NeedCount;	//! [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32 TaskEvent;	//! [TRANSLATED][TRANSLATED]event
	INT32  NeedLevel;	//! [TRANSLATED][TRANSLATED]Level
	UINT32 AwardID;		//! [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]ID
};

struct StStoreItemInfo
{
	UINT32 StoreID;		//! [TRANSLATED][TRANSLATED]ID
	UINT32 ItemID;
	UINT32 ItemNum;
	UINT32 CostMoneyID;
	UINT32 CostMoneyNum;
	UINT32 StoreType;
};

struct StActivityInfo
{
	UINT32 ActivityID;		//! [TRANSLATED][TRANSLATED]ID
	std::string Name;
	std::string Desc;
	std::string Ad;
	UINT32 Statue;
	UINT32 ActivityType;
	UINT32 AwardIndex;
	UINT32 StartTime;
	UINT32 EndTime;
};

#endif //__STATIC_STRUCT_H__