/* NOTE: original file backed up at /tmp/chinese_backups/Server___Src___ServerData___ServerStruct.h */
#ifndef __SERVER_STRUCT_H__
#define __SERVER_STRUCT_H__

struct BattleRecord
{
	UINT32			m_dwResult;		//0:[TRANSLATED][TRANSLATED][TRANSLATED]，1:[TRANSLATED][TRANSLATED]，2: Failure 3: [TRANSLATED][TRANSLATED]
	UINT32			m_dwKill;		//[TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32          m_dwDeath;		//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32			m_dwHeal;		//[TRANSLATED][TRANSLATED][TRANSLATED]
	UINT32          m_dwDamage;		//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
};

enum EChangeType
{
	ECT_EQUIP = 1,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	ECT_MOUNT = 2,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	ECT_LEVEL = 3,//Level
	ECT_PARTNER = 4,//[TRANSLATED][TRANSLATED]
	ECT_PET = 5,//[TRANSLATED][TRANSLATED]
};

enum EWinCondition
{
	EWC_NONE,
	EWC_KILL_ALL,       //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	EWC_KILL_NUM,       //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]count[TRANSLATED][TRANSLATED]
	EWC_DESTINATION,    //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	EWC_PLAYER_ALIVE,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	EWC_NPC_ALIVE,      //[TRANSLATED][TRANSLATED]npc
	EWC_END
};

enum EBattleCamp
{
	EBC_NONE,     //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	EBC_PLAYER,   //player[TRANSLATED][TRANSLATED]
	EBC_MONSTER,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
};

enum ETriggerType
{
	ETT_NORMAL,     //[TRANSLATED][TRANSLATED]trigger
	ETT_TRIBOX,     //trigger[TRANSLATED]trigger
	ETT_TIME,       //[TRANSLATED][TRANSLATED]trigger
};


#endif //__SERVER_STRUCT_H__