syntax = "proto3";
enum EObjectType {
    OT_NONE   = 0;
    OT_PLAYER = 1;  //Player
    OT_NPC    = 2;  //NPC
    OT_MONSTER= 3;  //Monster
    OT_PET    = 4;  //Pet
    OT_MOUNT  = 5;  //Mount
    OT_MACHINE= 6;  //Machine
    OT_PARTNER= 7;  //Partner
    OT_SUMMON = 8;  //Summon
}

enum EActionType {
    AT_NONE         = 0;    //None
    AT_IDLE         = 1;    //Idle
    AT_FIXBODY      = 2;    //Fix body
    AT_WALK         = 3;    //Walk
    AT_RUN          = 4;    //Run
    AT_FLY          = 5;    //Fly
    
    AT_SKILL        = 6;    //Skill
    AT_MINE         = 7;    //Mine
    AT_ROLL         = 8;    //Roll
    AT_JUMP         = 9;    //Jump
    AT_BORN         = 10;   //Born
    AT_DANCE        = 11;   //Dance
    
    AT_DEAD         = 12;   //Dead
    AT_WOUND        = 13;   //Wound
    AT_BEATBACK     = 14;   //Beat back
    AT_BEATDOWN     = 15;   //Beat down
    AT_BEATFLY      = 16;   //Beat fly
}

enum EActionStatue {
    AS_NONE         = 0;          //No action
    AS_HURT         = 0x1;        //Hurt
    AS_START        = 0x2;        //Start action
    AS_END          = 0xfffffff;  //Skill action start
}
    
enum ECopyType {
    CPT_NONE     = 0;        //No camp
    CPT_LOGIN    = 1;        //Login copy
    CPT_SELROLE  = 2;        //Select role copy
    CPT_CITY     = 3;        //Main city
    CPT_MAIN     = 4;        //Main line copy
    CPT_WORLD    = 5;        //World
    CPT_END = 100;
}

enum EObjectStatus
{
    EOS_NONE            = 0;//None
    EOS_DEAD            = 1;//Dead
    EOS_NOT_MOVE        = 2;//Cannot move
    EOS_NOT_CAST        = 3;//Cannot cast skill
    EOS_NOT_BEHURT      = 4;//Cannot be attacked
    EOS_NOT_BECONTROL   = 5;//Cannot be controlled
    EOS_STEALTH         = 6;//Cannot be seen
    EOS_BLIND           = 7;//Cannot see others
};


enum EItemType
{
    EIT_NONE         = 0;
    EIT_MONEY        = 1;
    EIT_ACTION       = 2;
    EIT_ITEM         = 3;
    EIT_EQUIP        = 4;
    EIT_GEM          = 5;
    EIT_RELICS       = 6;
    EIT_MOUNT        = 7;
    EIT_PET          = 8;
    EIT_PARTNER      = 9;
    EIT_FASHION      = 10;
    EIT_BOX          = 11;
    EIT_ACTBOX       = 12;
    EIT_CHIP         = 13; 
    EIT_RUNE         = 14;
    EIT_DRUG         = 15;
}

enum EBagType
{
    EBT_NONE    = 0;
    EBT_ITEM    = 1;
    EBT_GEM     = 2;
    EBT_FASHION = 3;
    EBT_CHIP    = 4;
    EBT_RUNE    = 5;
    EBT_TASK    = 6;
    EBT_SOUL    = 7;
    EBT_CARD    = 8;  //Hero card
}

enum EFunctionType{
    FUNC_BEGIN_ID  = 0;  //!Function ID start marker
    
    FUNC_END_ID = 150; //!Function ID end marker
}

enum EAttrID{
    EA_HP            = 0;  //HP
    EA_MP            = 1;  //MP
    EA_HP_MAX        = 2;  //Max HP
    EA_MP_MAX        = 3;  //Max MP
    EA_SPEED         = 4;  //Movement speed
    EA_ATTACK        = 5;  //Attack
    EA_ELEMENT       = 6;  //Element damage
    EA_MAGIC_DEF     = 7;  //Magic defense
    EA_PHYSIC_DEF    = 8;  //Physical defense
    EA_HIT_RATE      = 9; //Hit rate
    EA_DODGE         = 10; //Dodge
    EA_MORE_HURT     = 11; //More hurt
    EA_LESS_HURT     = 12; //Less hurt
    EA_CRIT_HIT      = 13; //Critical hit
    EA_CRIT_DEF      = 14; //Critical defense
    EA_CRIT_HURT     = 15; //Critical hurt
    EA_ATTR_NUM      = 16; //Attribute count
}

enum EShip
{
    ES_NEUTRAL =  0;
    ES_FRIEND  =  1;
    ES_ENEMY   =  2;
}

enum EHitShipType
{
    EHST_ALL        = 0;      // All targets
    EHST_FRIEND     = 1;      // Target must be friendly to cast
    EHST_ENEMY      = 2;      // Target must be enemy to cast
}

enum EBuffType{
    BFT_NONE        = 0; 
}

enum EChatChannel{
    CHL_NONE        = 0; 
    CHL_WORLD       = 1;//World chat
    CHL_PRIVATE     = 2;//Private chat
    CHL_GUILD       = 3;//Guild
    CHL_ROLLTIP     = 4;//Roll tip
}

enum EEquipPos{
    EEP_NONE        = 0; 
    EEP_HELMET      = 1; 
    EEP_NECKLACE    = 2; 
    EEP_ARMOR       = 3; 
    EEP_SHOES       = 4; 
    EEP_WRIST       = 5; 
    EEP_RING        = 6; 
    EEP_TALISMAN    = 7; 
    EEP_WEAPON      = 8; 
}

enum ETaskStatus{
    ETS_INIT        = 0; 
    ETS_ACCEPT      = 1; 
    ETS_FINISH      = 2; 
    ETS_COMMIT      = 3;
}

//Copy battle result
enum ECopyResult
{
	ECR_NONE    = 0;    //Not settled
	ECR_WIN     = 1;    //Win
	ECR_LOST    = 2;    //Lost
	ECR_DRAW    = 3;    //Draw
};

enum EGuildPos
{
	EGP_MEMBER		= 0;
	EGP_LEADER		= 1;
	EGP_VICELEADER  = 2;
}

enum EMailType
{
	EMT_BEGIN		= 0;   //Invalid value
	EMT_CUSTOM		= 1;   //Custom mail
}

enum EMailStatus
{
	EMS_NEWMAIL		= 0;   //New mail
	EMS_RECEIVED	= 1;   //Reward already received
}