syntax = "proto3";

message DBRoleData {
    uint64      AccountID    = 1;
    uint64      RoleID       = 2;
    int32       CarrerID     = 3;
    int32       Level        = 4;
    int64       Exp          = 5;
    string      Name         = 6;
    int32       LangID       = 7;
    int32       VipLvl        = 8;
    int32       VipExp       = 9;
    int64       FightValue   = 10;
    int32       CityCopyID   = 11;
    repeated    int64 Action = 12;
    repeated    int64 Actime = 13;
    uint64      CreateTime   = 14;
    uint64      LogonTime    = 15;
    uint64      LogoffTime   = 16;
    uint64      GuildID      = 17;
    int32       Channel      = 18;
    uint32      OnlineTime    = 19;
}

message DBBagItem {
    uint64    Guid = 1;            //Grid guid
    uint64    RoleID = 2;            //Role ID
    uint64    ItemGuid = 3;        //Item guid
    uint32    ItemID = 4;            //Item ID
    int64     Count = 5;            //Count
    int32     Bind = 6;            //Whether bound
    int32     Status = 7;            //Whether deleted
}

message DBBagData {
    repeated DBBagItem ItemList = 1;
}

message DBCopyItem {
    uint64  RoleID = 1;            //Role ID
    uint32  CopyID = 2;
    int32   StarNum = 3;
    int32   BattleCnt = 4;
    int32   ResetCnt = 5;
    uint64  BattleTime = 6;
    uint64  ResetTime = 7;
}

message DBChapterItem {
    uint64  RoleID = 1;            //Role ID
    uint32  CopyType = 2;
    uint32  ChapterID = 3;
    uint32  StarAward = 4;
    uint32  SceneAward = 5;
}

message DBCopyData {
    repeated DBCopyItem CopyList = 1;
    repeated DBChapterItem ChapterList = 2;
}

message DBEquipItem {
    uint64   RoleID = 1;         //Role ID
    uint64   Guid = 2;
    int32    EquipID = 3;
    int32    StrengthLvl = 4;   //Enhancement level
    int32    RefineLevel = 5;   //Refinement level
    int32    StarLevel = 6;      //Star level
    int32    RefineExp = 7;      //Refinement experience
    int32    StarExp = 8;      //Star level experience
    bool     IsUsing = 9;       //Whether in use
}

message DBEquipData {
    repeated    DBEquipItem EquipList = 1;
}

message DBGemItem {
    uint64   RoleID = 1;         //Role ID
    uint64   Guid = 2;
    int32    GemID = 3;
    int32    StrengthLvl = 4;   //Enhancement level
    int32    RefineLevel = 5;   //Refinement level
    int32    StarLevel = 6;      //Star level
    int32    RefineExp = 7;      //Refinement experience
    int32    StarExp = 8;          //Star level experience
    int32    Pos = 9;        //Position
}

message DBGemData {
    repeated    DBGemItem GemList = 1;
}


message DBSkillItem {
    uint64   RoleID = 1;         //Role ID
    uint32   SkillID = 2;        //Skill ID
    int32    Level = 3;          //Skill level
    int32    KeyPos = 4;         //Key position
}

message DBSkillData {
    repeated    DBSkillItem SkillList = 1;
}


message DBPetItem {
    uint64   RoleID = 1;         //Role ID
    uint64   Guid = 2;
    int32    PetID = 3;
    int32    StrengthLvl = 4;   //Enhancement level
    int32    RefineLevel = 5;   //Refinement level
    int32    StarLevel = 6;      //Star level
    bool     IsUsing = 7;       //Whether in use
}

message DBPetData {
    repeated    DBPetItem PetList = 1;
}

message DBMountItem {
    uint64   RoleID = 1;         //Role ID
    uint64   Guid = 2;
    int32    MountID = 3;
    int32    StrengthLvl = 4;   //Enhancement level
    int32    RefineLevel = 5;   //Refinement level
    int32    StarLevel = 6;      //Star level
    bool     IsUsing = 7;       //Whether in use
}

message DBMountData {
    repeated    DBMountItem MountList = 1;
}

message DBPartnerItem {
    uint64   RoleID = 1;         //Role ID
    uint64   Guid = 2;
    int32    PartnerID = 3;
    int32    StrengthLvl = 4;   //Enhancement level
    int32    RefineLevel = 5;   //Refinement level
    int32    StarLevel = 6;      //Star level
    int32    SetPos = 7;       //Formation position
}

message DBPartnerData {
    repeated DBPartnerItem PartnerList = 1;
}

message DBTaskItem {
    uint64  RoleID = 1;            //Role ID
    uint32  TaskID = 2;
    int32   Status = 3;
    int32   Progress = 4;
}

message DBTaskData {
    repeated DBTaskItem TaskList = 1;
}

message DBMailItem {
    uint64   RoleID    = 1;   //Role ID
    uint64   Guid      = 2;   //Mail GUID
    uint64   GroupID   = 3;   //Group mail GUID
    uint64   Time      = 4;   //Mail time
    uint64   SenderID  = 5;   //Sender ID
    string   Sender    = 6;   //Sender name
    uint32   MailType  = 7;
    uint32   Status    = 8;
    string   Title     = 9;   //Mail title
    string   Content   = 10;  //Mail content
    bytes    Items     = 11;  //Mail items
}

message DBMailData {
    repeated DBMailItem MailList = 1;
}

message DBActivityItem {
    uint64    RoleID = 1;            //Role ID
    uint32    ActivityID = 2;  //Activity ID
    uint32    ActivityType = 3;//Activity type
    uint32    JoinTime = 4;    //Join time
    uint32    DataLen = 5;     //Data length
    bytes     Data = 6;    //Activity data
}

message DBActivityData {
    repeated DBActivityItem ActivityList = 1;
}


message DBCounterItem {
    uint64    RoleID       = 1;        //Role ID
    uint32    CounterID    = 2;        //Counter ID
    uint32    Index        = 3;        //Sub-index
    int64     Value        = 4;        //Counter value
    uint64    Time         = 5;        //Join time
    uint32    Param1       = 6;        //Parameter 1
    uint32    Param2       = 7;        //Parameter 2
}

message DBCounterData {
    repeated DBCounterItem CounterList = 1;
}


message DBFriendItem {
    uint64    RoleID        = 1;        //Role ID
    uint64    FriendID      = 2;        //Friend ID
}

message DBFriendData {
    repeated DBFriendItem FriendList = 1;
}

message DBRoleLoginAck {
    uint32              RetCode     = 1;
    uint64              RoleID      = 2;
    DBRoleData          RoleData    = 3;
    DBBagData           BagData     = 4;
    DBCopyData          CopyData    = 5;
    DBEquipData         EquipData   = 6;
    DBGemData           GemData     = 7;
    DBPetData           PetData     = 8;
    DBPartnerData       PartnerData = 9;
    DBTaskData          TaskData    = 10;
    DBMailData          MailData    = 11;
    DBMountData         MountData   = 12;
    DBActivityData      ActivityData= 13;
    DBCounterData       CounterData = 14;
    DBFriendData        FriendData  = 15;
    DBSkillData         SkillData   = 16;
}

