syntax = "proto3";

message CheckVersionReq {
    string   ClientVerion   = 1;  //Client version xxx.xxx.xxx
    int32    Channel        = 2;  //Channel ID  
}

message CheckVersionAck {
    uint32    RetCode        = 1;
    string    ClientVerion   = 2;
}

message AccountLog
{
    int32  Channel    = 1;   //Channel ID
    string Version    = 2;   //Version
    uint64 AccountID  = 3;   //Account
    string Uuid       = 4;   //Device UUID
    string Idfa       = 5;   //idfa
    string Imodel     = 6;   //Device model
    string Imei       = 7;   //Phone IMEI
    int32  IpAddr     = 8;   //IP address
}  

message AccountRegReq {
    string     AccountName = 1; //Account name
    string     Password    = 2; //Password
    int32      Channel     = 3; //Channel
    AccountLog RegLog      = 4; //Client information
}

message AccountRegAck {
    uint32    RetCode      = 1;
    uint64    AccountID    = 2; //Account ID
}

message AccountLoginReq {
    string     AccountName    = 1; //Account name
    string     Password       = 2; //Password
    int32      Channel        = 3; //Channel
    bool       FromChannel    = 4; //From channel
    bool       Review         = 5; //Whether review
    AccountLog LoginLog      = 6; //Login log
}

message AccountLoginAck {
    uint32    RetCode        = 1;
    uint64    AccountID      = 2;
    int32     LastSvrID      = 3;  //Last login SvrID
    string    LastSvrName    = 4;
    bool      Review         = 5; 
    int32     Channel        = 6;
    int32     IpAddr         = 7;   //IP address
}

message ClientServerListReq {
    uint64    AccountID      = 1;
    int32     Channel        = 2; //Channel package
    string    Version        = 3; //Client version
    bool      Review         = 4; 
}

message ClientServerNode {
    int32    SvrID          = 1;
    string   SvrName        = 2;
    int32    SvrFlag        = 3; //Server flag 0:Unknown, 1:Smooth,2:Crowded,3:Full,4:Maintenance,5:Closed 6:Review 
    int32    CornerMark     = 4; //Server corner mark 0:None, 1:New server,2:Recommended
    int64    SvrOpenTime    = 5; //Server open time
    int32    SvrStatus      = 6; //1: Server online, 0: Server offline
}

message ClientServerListAck {
    uint32    RetCode    = 1;
    repeated ClientServerNode SvrNode    = 2;
}

message SelectServerReq {
    uint64    AccountID   = 1;
    int32     ServerID    = 2;
    bool      CheckRole   = 3;  //Whether must have role
}

message SelectServerAck {
    uint32   RetCode     = 1;
    uint64   AccountID   = 2;
    int32    ServerID    = 3;
    string   ServerAddr  = 4; //Server address
    int32    ServerPort  = 5; //Server port
    int32    LoginCode   = 6; //Login verification code, client needs to use this code to connect to game server
}

message SealAccountReq {
    string    AccountName  = 1;
    uint64    AccountID    = 2;
    int32     Channel      = 3;
    int32     SealTime     = 4;
    bool      Seal         = 5;
}

message SealAccountAck {
    uint32    RetCode        = 1;
    string    AccountName    = 2;
    uint64    AccountID      = 3; //Account ID
    int32     ServerID       = 4; //Last login SvrID
}

message SealAccountNtf {
    uint64    AccountID      = 1; //Account ID
}

message SetLastServerNty {
    uint64    AccountID    = 1;
    int32     ServerID     = 2;
}