syntax = "proto3";
import "Msg_Base.proto";
//Request to cast skill
message SkillCastReq
{    
    uint64   ObjectGuid    = 1;
    int32    SkillID       = 2;
    float    HostX         = 3;
    float    HostY         = 4;
    float    HostZ         = 5;
    float    HostFt        = 6;
    float    TargetX       = 7;
    float    TargetY       = 8;
    float    TargetZ       = 9;
    float    TargetFt      = 10;
    repeated uint64 TargetObjects = 11;
}

//Skill cast request response (if casting is allowed, this response is not sent)
message SkillCastAck
{    
    uint32    RetCode = 1;  //Whether casting succeeded, failure reason
    uint64    ObjectGuid = 2; //Object that cast the skill
}

//Skill cast result
message SkillResultItem
{    
    uint64  ObjectGuid  = 1;    //Target's ID
    int32   SkillID     = 2;    //Which skill hit
    int32   ActionID    = 3;    //What action is needed now
    float   OrgX        = 4;    //Coordinates when hit
    float   OrgY        = 5;    //Coordinates when hit
    float   OrgZ        = 6;    //Coordinates when hit
    float   OrgFt       = 7;    //Direction when hit
    int32   HpChange    = 8;    //Changed HP
    bool    bCrit       = 9;    //Whether critical hit
}

//Skill cast result
message SkillResultNtf
{    
    repeated SkillResultItem ItemList = 1;
}

//Movement action request
message ObjectActionReq {
   repeated    ActionReqItem ActionList = 1;
}

//Movement action request
message ObjectActionNty {
   repeated ActionNtyItem ActionList = 1;
}

message ActionReqItem {
    uint64   ObjectGuid  = 1;
    int32    ActionID    = 2;
    float    HostX       = 3;
    float    HostY       = 4;
    float    HostZ       = 5;
    float    HostFt      = 6;
}


message ObjectActionAck {
   repeated    ActionReqItem ActionList = 1;
}

message ActionNtyItem {
    uint64   ObjectGuid    = 1;
    int32    ActionID      = 2;        
    int32    Camp          = 3;        //Camp
    int32    ObjectStatus  = 4;        //Object status
    int32     Speed        = 5;
    float    HostX         = 6;
    float    HostY         = 7;
    float    HostZ         = 8;
    float    HostFt        = 9;
    int32    ActorID       = 10;        //Actor ID
    int32    MountID       = 11;        //Mount ID
    int32    Level         = 12;        //Level
    uint64   ControlerID   = 13;        //AI controller's GUID
    int32    Hp            = 14;
    int32    Mp            = 15;
    int32    HpMax         = 16;
    int32    MpMax         = 17;
    repeated int32 Equips  = 18;         //Equipment
}

message NewItem {
    uint64    ObjectGuid    = 1;        //Instance ID
    int32     ActionID      = 2;        
    int32     ObjType       = 3;        //Object type
    int32     ObjectStatus  = 4;        //Instance status
    int32     ActorID       = 5;        //Actor ID
    int32     MountID       = 6;        //Mount ID
    int32     Camp          = 7;        //Camp
    string    Name          = 8;        //Name
    int32     Level         = 9;        //Level
    int32     Speed         = 10;
    uint64    HostGuid      = 11;       //Owner's GUID
    uint64    ControlerID   = 12;       //AI controller's GUID
    uint64    SummonID      = 13;       //Summoner's GUID
    float     X             = 14;        
    float     Y             = 15;
    float     Z             = 16;
    float     Ft            = 17;
    int32     Hp            = 18;
    int32     Mp            = 19;
    int32     HpMax         = 20;
    int32     MpMax         = 21;
    repeated int32 Equips   = 22;       //Equipment
    repeated SkillItem Skills= 23;      //Normal skills
}

message ObjectNewNty {
  repeated NewItem NewList = 1;
}

message ObjectRemoveNty {
  repeated uint64 RemoveList = 1;
}

//Bullet object
message BulletItem
{    
    uint64  ObjectGuid  = 1;    //Object ID
    uint64  TargetGuid  = 2;    //Target GUID
    uint64  CasterGuid  = 3;    //Caster GUID
    int32   BulletID    = 4;    //Bullet's ID
    float   X           = 5;    //Coordinate X
    float   Y           = 6;    //Coordinate Y
    float   Z           = 7;    //Coordinate Z
    float   Angle       = 8;    //Angle
    float   Speed       = 9;   //Speed
    float   AccSpeed    = 10;   //Acceleration
    float   LifeTime    = 11;   //Total lifetime
    float   LeftTime    = 12;   //Remaining time
}

//Skill cast result
message BulletNewNtf
{    
    repeated BulletItem ItemList = 1;
}

message HeartBeatReq {
  uint32  TimeStamp = 1;
}

message HeartBeatAck {
  uint32  TimeStamp = 1;
  uint32  ServerTime = 2;
}

message ObjectDieNotify {
  uint64  ObjectGuid = 1;
}

message Msg_RidingMountReq {
   uint64   ObjectGuid    = 1;
}

message Msg_RidingMountAck {
  uint32    RetCode = 1;  //Whether successful, failure reason.
}


message Msg_RoleRebornReq {
   uint64   ObjectGuid    = 1;
   int32    RebornType    = 2;
}

message Msg_RoleRebornAck {
  uint32    RetCode = 1;  //Whether successful, failure reason.
}