syntax = "proto3";

enum MessageRetCode {
    //System reserved
    MRC_SUCCESSED        = 0;    //Success
    MRC_UNKNOW_ERROR     = 1;    //Unknown error
    MRC_DISCONNECT       = 2;    //Connection disconnected
    
     //Invalid
    MRC_INVALID_ACCNAME   = 100;    //Invalid account name
    MRC_INVALID_ACCID     = 101;    //Invalid account ID
    MRC_INVALID_PASSWORD  = 102;    //Invalid password
    MRC_INVALID_NAME      = 103;    //Invalid name
    MRC_INVALID_ROLEID    = 104;    //Invalid role ID
    MRC_INVALID_ITEMID    = 105;    //Invalid item ID
    MRC_INVALID_COPYID    = 106;    //Invalid copy ID
    MRC_INVALID_PETID     = 107;    //Invalid pet ID
    MRC_INVALID_PARTNERID = 108;    //Invalid partner ID
    MRC_INVALID_EQUIP_ID  = 109;    //Invalid equip ID
    MRC_INVALID_CARRERID  = 110;    //Invalid career ID
    MRC_INVALID_SKILL_ID  = 111;    //Invalid skill ID
    MRC_INVALID_TARGET_ID = 112;    //Invalid target ID
    MRC_INVALID_SERVER_ID = 113;    //Invalid server ID
    MRC_INVALID_GIFT_CODE = 114;    //Invalid gift code
   
       //Insufficient conditions
    MRC_NOT_ENOUGH_ACTOIN     = 200;    //Insufficient action points
    MRC_NOT_ENOUGH_MONEY      = 201;    //Insufficient money
    MRC_NOT_ENOUGH_ITEM       = 202;    //Insufficient items
    MRC_NOT_ENOUGH_TIMES      = 203;    //Insufficient times
    MRC_NOT_ENOUGH_LEVEL      = 204;    //Insufficient level
    MRC_NOT_ENOUGH_VIPLV      = 205;    //Insufficient VIP level
    MRC_ERROR_SEAL_ROLE       = 206;   //Role has been sealed
    MRC_NAME_ERROR_FMT        = 207;   //Name does not meet requirements
    MRC_REPEAT_LOGIN          = 208;   //Repeat login
   
    //Other
    MRC_ACCOUNT_NAME_EXIST     = 300;    //Account name already exists
    MRC_ACCOUNT_NAME_NOT_EXIST = 301;    //Account name does not exist
    MRC_ACCOUNT_NAME_ERR_FMT   = 302;    //Account name does not meet requirements
    MRC_ROLE_NAME_EXIST        = 303;    //Role name already exists
    MRC_ACCOUNT_SEALED         = 304;    //Account sealed
    MRC_ACCOUNT_WRONG_VERSION  = 305;    //Client version incorrect
    MRC_ACCOUNT_WRONG_PASSWORD = 306;    //Client version incorrect
    MRC_ROLE_NAME_MUST_UTF8    = 308;   //Name must be UTF8 encoded
    MRC_ROLE_SEALED            = 309;   //Role has been sealed
    MRC_ROLE_DELETED           = 310;   //Role deleted
    MRC_ILLEGAL_LOGIN_REQ      = 311;    //Illegal login request
    MRC_KICKOUT_BY_OTHER      = 312;    //Kicked out by others
    MRC_SERVER_NOT_OPENTIME   = 313;   //Not yet server open time
    MRC_SERVER_NOT_AVAILABLE  = 314;   //Server not available
    MRC_SERVER_MAINTAIN       = 315;   //Server maintenance
    MRC_SERVER_NO_NEW_ROLE    = 316;   //No new roles allowed
    MRC_CANNOT_RECONNECT      = 317;     //Cannot reconnect

    //Skill
    MRC_SKILL_CD_ERROR        = 401;    //Skill not cooled down    
    MRC_SKILL_DEAD_OBJ        = 402;    //Object already dead
    MRC_DUPLICATED_ORDER_ID   = 403;   //Duplicate order creation
    
       //Gift code
    MRC_GIFTCODE_AREADY_USED   = 500;    //Gift code already used
    MRC_GIFTCODE_INVALIDE_CODE = 501;    //Invalid gift code
    MRC_GIFTCODE_UNASSIGNED    = 502;    //Gift code unassigned
    MRC_GIFTCODE_WRONG_CHANNEL = 503;    //Wrong channel
    MRC_GIFTCODE_WRONG_AREA    = 504;    //Wrong area
    MRC_GIFTCODE_NO_MORE       = 505;    //Already claimed
}

