/* NOTE: original file backed up at /tmp/chinese_backups/Client___Assets___Scripts___GamePlay___ACT___ActDefine.cs */
﻿using UnityEngine;
using System.Collections;

public enum ESkillPos
{
    Skill_0,
    Skill_1,
    Skill_2,
    Skill_3,
    Skill_4,
    Skill_5,
    Skill_6,
    Skill_7,
    Skill_8,
    Skill_9,
}

public enum EActType
{
    TYPE_NONE             = 0,

    TYPE_ADDATTR          = 1,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SUBATTR          = 2,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_HOT              = 3,  //HOT
    TYPE_DOT              = 4,  //DOT
    TYPE_SUPER            = 5,  //[TRANSLATED][TRANSLATED]
    TYPE_VARIATION        = 6,  //[TRANSLATED][TRANSLATED]
    TYPE_STUN             = 7,  //[TRANSLATED][TRANSLATED]
    TYPE_FIXBODY          = 8,  //[TRANSLATED][TRANSLATED]
    TYPE_STEALTH          = 9,  //[TRANSLATED][TRANSLATED]
    TYPE_FROZEN           = 10, //[TRANSLATED][TRANSLATED]

    TYPE_BLIND            = 11, //[TRANSLATED][TRANSLATED]
    TYPE_SILENT           = 12, //[TRANSLATED][TRANSLATED]
    TYPE_SLEEP            = 13, //[TRANSLATED][TRANSLATED]
    TYPE_ABSORB           = 14, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SUCKBLOOD        = 15, //[TRANSLATED][TRANSLATED]
    TYPE_DIVIVE           = 16, //[TRANSLATED][TRANSLATED]
    TYPE_PARALY           = 17, //[TRANSLATED][TRANSLATED]
    TYPE_FEAR             = 18, //[TRANSLATED][TRANSLATED]
    TYPE_REFLEX           = 19, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_TIMEDDEATH       = 20, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_FLASH            = 21, //[TRANSLATED][TRANSLATED]
    TYPE_SPURT            = 22, //[TRANSLATED][TRANSLATED]
    TYPE_BEATFLY          = 23, //[TRANSLATED][TRANSLATED]
    TYPE_BEATDOWN         = 24, //[TRANSLATED][TRANSLATED]
    TYPE_BEATBACK         = 25, //[TRANSLATED][TRANSLATED]
    TYPE_HIT              = 26, //hit
    TYPE_ANIM             = 27, //[TRANSLATED][TRANSLATED]
    TYPE_AUDIO            = 28, //[TRANSLATED][TRANSLATED]
    TYPE_AUDIOLOOP        = 29, //[TRANSLATED][TRANSLATED]Loop

    TYPE_FLOAT            = 31, //[TRANSLATED][TRANSLATED]
    TYPE_PUSH             = 32, //[TRANSLATED][TRANSLATED]
    TYPE_FACETOTARGET     = 33, //[TRANSLATED][TRANSLATED]
    TYPE_TAUNT            = 34, //[TRANSLATED][TRANSLATED]
    TYPE_GATHER           = 35, //[TRANSLATED][TRANSLATED]
    TYPE_FALSEDEAD        = 36, //[TRANSLATED][TRANSLATED]

    TYPE_BEAM             = 40, //[TRANSLATED][TRANSLATED]
    TYPE_TRIGGER          = 41, //trigger[TRANSLATED]
    TYPE_EFFECT           = 42, //effect
    TYPE_FLYWEAPON        = 43, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_LIGHTING         = 44, //[TRANSLATED][TRANSLATED]
    TYPE_MISSILE          = 45, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RAY              = 46, //[TRANSLATED][TRANSLATED]
    TYPE_WALL             = 47, //[TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BINDEFFECT       = 48, //[TRANSLATED][TRANSLATED]effect
    TYPE_SUMMON           = 49, //[TRANSLATED][TRANSLATED]

    TYPE_MOVE             = 56, //[TRANSLATED][TRANSLATED]
    TYPE_THROUGHMOVESTART = 57, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]begin
    TYPE_THROUGHMOVE      = 58, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_THROUGHMOVEEND   = 59, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]end

    TYPE_DAMAGE           = 62, //[TRANSLATED][TRANSLATED]
    TYPE_HEAL             = 63, //[TRANSLATED][TRANSLATED]


    TYPE_SCOPESPHERE      = 71, //[TRANSLATED][TRANSLATED]range[TRANSLATED][TRANSLATED]target
    TYPE_SCOPECYLINDER    = 72, //[TRANSLATED][TRANSLATED]range[TRANSLATED][TRANSLATED]target
    TYPE_SCOPEBOX         = 73, //[TRANSLATED][TRANSLATED]range[TRANSLATED][TRANSLATED]target
    TYPE_SCOPETRIANGLE    = 74, //[TRANSLATED][TRANSLATED]range[TRANSLATED][TRANSLATED]target
    TYPE_ADDBUFF          = 75, //[TRANSLATED][TRANSLATED]BUFF
    TYPE_DISPEL           = 76, //[TRANSLATED][TRANSLATED]
    TYPE_STEALBUFF        = 77, //[TRANSLATED][TRANSLATED]BUFF
    TYPE_WRITEWHEELEYE    = 78, //[TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_AURA             = 79, //[TRANSLATED][TRANSLATED]

    TYPE_SHADER           = 81, //Shader[TRANSLATED][TRANSLATED]
    TYPE_SCALE            = 82, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_MATERIAL         = 83, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_COLORSKY         = 85, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SHAKE            = 86, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ROTATE           = 87, //[TRANSLATED][TRANSLATED]
    TYPE_TIMESCALE        = 88, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_HIDEWEAPON       = 89, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_RESETSKILLCD     = 91, //[TRANSLATED][TRANSLATED]Skill CD
    TYPE_SHORTENSKILLCD   = 92, //[TRANSLATED][TRANSLATED]Skill CD
    TYPE_EXTENDSKILLID    = 93, //[TRANSLATED][TRANSLATED]Skill CD
    TYPE_BREAKSKILL       = 94, //[TRANSLATED][TRANSLATED]skill
    TYPE_UPSKILLRESULT    = 95, //[TRANSLATED][TRANSLATED]skill[TRANSLATED][TRANSLATED]
    TYPE_CHANGESKILL      = 96, //[TRANSLATED][TRANSLATED][TRANSLATED]skill[TRANSLATED][TRANSLATED]is[TRANSLATED][TRANSLATED]skill

    TYPE_PROBABLY         = 101, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SEQUENCE         = 102, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CLONE            = 103, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RANDOM           = 104, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RANDOMMANY       = 105, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_TREE             = 106,
    TYPE_LOG              = 107,
}

public enum ESkillCostType
{
    NO,
    MP = 1,//[TRANSLATED][TRANSLATED]
    HP = 2,//life
    SP = 3,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    XP = 4,//[TRANSLATED][TRANSLATED]
}

public enum ESkillType
{
    Postive = 0,//[TRANSLATED][TRANSLATED]
    Passive = 1,//[TRANSLATED][TRANSLATED]
}

public enum ESkillMoveType
{
    TYPE_CANNOT_MOVE = 0,
    TYPE_NOANIM_MOVE = 1,
    TYPE_IKANIM_MOVE = 2,
}

public enum EDamageType
{
    TYPE_PHYSICS = 0,//[TRANSLATED][TRANSLATED]
    TYPE_FIRE    = 1,//[TRANSLATED][TRANSLATED]
    TYPE_ICE     = 2,//[TRANSLATED][TRANSLATED]
    TYPE_DARK    = 3,//[TRANSLATED][TRANSLATED]
    TYPE_LIGHT   = 4 //[TRANSLATED][TRANSLATED]
}


public enum ESelectTarget
{
    TYPE_CASTER     = 0,
    TYPE_TARGET     = 1,
    TYPE_TARGETLIST = 2,
}

public enum ESelectTargetPolicy
{
    Normal = 0,
    MaxHP  = 1,
    MinHP  = 2,
    MaxDis = 3,
    MinDis = 4,
}

public enum EActStatus
{
    INITIAL,//[TRANSLATED][TRANSLATED][TRANSLATED]
    STARTUP,//begin
    TRIGGER,//trigger
    RUNNING,//running
    SELFEND,//[TRANSLATED][TRANSLATED]runningend
    SUCCESS,//Success
}


public enum ESkillBreakReason
{
    TYPE_NONE,      //[TRANSLATED]
    TYPE_BUFF,      //Buff[TRANSLATED][TRANSLATED]
    TYPE_STIFF,     //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_NEWSKILL,  //[TRANSLATED]skill[TRANSLATED][TRANSLATED]
    TYPE_BEDAMAGE,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SPECIAL,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}


public enum EActEventType
{
    Special,//[TRANSLATED][TRANSLATED]
    Instant,//[TRANSLATED][TRANSLATED]
    Subtain,//[TRANSLATED][TRANSLATED]
}

public enum EnumCameraShake
{
    Horizontal,             //[TRANSLATED][TRANSLATED]
    Vertical,               //[TRANSLATED][TRANSLATED]
    HorizontalAndVertical   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}

//Buffstacktype
public enum EBuffOverlayType
{
    UnChange,
    Overlay,
    Refresh,
    OverlayAndRefresh,
}

//Buff[TRANSLATED][TRANSLATED]type
public enum EBuffDestroyType
{
    BY_NONE       = 0,
    BY_BATTLEEND  = 1,
    BY_TIMEEND    = 2,
    BY_OFFLINE    = 3,
    BY_DEAD       = 4,
    BY_NEXTATTACK = 5,
    BY_ALL        = 6,
}

public enum EBuffType
{
    None,
    Buff,
    Debuff,
}


//effect[TRANSLATED][TRANSLATED]position
public enum EBind
{
    None  =-1,
    Head  = 0, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]position
    Body  = 1, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]position
    Foot  = 2, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]position
    LHand = 3, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    RHand = 4, //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    Buff  = 5, //Buff[TRANSLATED]
}

public enum EBindTarget
{
    TYPE_CASTER = 0,
    TYPE_TARGET = 1,
}

//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
public enum EMoveToward
{
    MoveToTarget,
    MoveToForward,
}

public enum EEffectType
{
    UV,
    PA,
    EP,
    TR,
}

public enum EEffectPeform
{
    TYPE_SWORD      = 1,
    TYPE_MISSILE    = 2,
    TYPE_RELICS     = 3,
    TYPE_AOE        = 4,
    TYPE_BORNORDEAD = 5,
    TYPE_LIGHT      = 6,
    TYPE_HIT        = 7,
    TYPE_BUFF       = 8,
}

public enum EHealType
{
    HP = 0,
    MP = 1,
    SP = 2
}