/* NOTE: original file backed up at /tmp/chinese_backups/Server___Src___ServerEngine___PacketHeader.h */
﻿#ifndef __PACKET__HEADER_H__
#define __PACKET__HEADER_H__

#pragma  pack(push)
#pragma  pack(1)

#define CODE_VALUE 0x88

struct PacketHeader
{
    INT32   CheckCode;
    INT32    nMsgID;
    INT32    nSize;
    INT32    nPacketNo;    //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] = nMsgID^nSize+index([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]); [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] = pHeader->dwPacketNo - pHeader->nMsgID^pHeader->nSize;
    UINT64   u64TargetID;
    UINT32   dwUserData;    //client[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]，dwUserData[TRANSLATED]copyguid， [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]， [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]clientconnectionID
};

struct PacketHeader2
{
    UINT32   CheckCode: 8;
    UINT32   dwSize : 24;
    UINT32   dwPacketNo : 8;    //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] = nMsgID^nSize+index([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]); [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] = pHeader->dwPacketNo - pHeader->nMsgID^pHeader->nSize;
    UINT32   Compress : 1;
    UINT32   Encrypt : 1;
    UINT32   nMsgID: 22;
    UINT64   u64TargetID;
    UINT32   dwUserData;    //client[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]，dwUserData[TRANSLATED]copyguid， [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]， [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]clientconnectionID
};


#pragma  pack(pop)



#endif /* __PACKET__HEADER_H__*/
