/* NOTE: original file backed up at /tmp/chinese_backups/Server___Src___GameServer___GridManager.h */
﻿#ifndef __GRID_MANAGER_H__
#define __GRID_MANAGER_H__
#include "Grid.h"

class CGridManager : public std::vector<CGrid>
{
public:
	CGridManager(void);
	~CGridManager(void);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		Init(INT32 nLeft, INT32 nRight, INT32 nTop, INT32 nBottom);

	//[TRANSLATED][TRANSLATED]position[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	CGrid*		GetGridByPos(FLOAT x, FLOAT z);

	//[TRANSLATED][TRANSLATED]position[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	INT32		GetIndexByPos(FLOAT x, FLOAT z);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	CGrid*		GetGridByIndex(INT32 nIndex);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		AddObjectToGrid(CMapObject* pMapObject, FLOAT x, FLOAT z);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		AddObjectToGrid(CMapObject* pMapObject, INT32 nIndex);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		RemoveObjectFromGrid(CMapObject* pMapObject, FLOAT x, FLOAT z);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		RemoveObjectFromGrid(CMapObject* pMapObject, INT32 nIndex);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		CalDiffGrids( INT32 nSrcIndex, INT32 nDestIndex, INT32 IncGrids[10], INT32 DecGrids[10], INT32 StayGrids[10]);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		GetSurroundingGrids(INT32 nIndex, INT32 sGridsp[10]);

	//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
	BOOL		IsObjectExist(CMapObject* pMapObject, INT32 nIndex);

public:

	INT32	m_nMaxRows;
	INT32	m_nMaxCols;

	INT32	m_nLeft, m_nRight, m_nTop, m_nBottom;
};

#endif /*__GRID_MANAGER_H__*/