/* NOTE: original file backed up at /tmp/chinese_backups/Client___Assets___Scripts___Frameworks___GTEventID.cs */
﻿using UnityEngine;
using System.Collections;

public enum GTEventID : ushort
{
    TYPE_NETWORK_CONNECT             = 1000,   //[TRANSLATED][TRANSLATED]connection
    TYPE_NETWORK_CONNECT_FAIL        = 1001,   //connectionFailure  
    TYPE_NETWORK_CONNECT_SUCCESS     = 1002,   //connectionSuccess

    TYPE_LOGIN_ACCOUNT_REGISTER      = 1051,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]            
    TYPE_LOGIN_ACCOUNT_LOGIN         = 1052,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] 
    TYPE_LOGIN_ROLECRATE             = 1053,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_LOGIN_SELECTSERVER          = 1054,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_LOGIN_ROLELOGIN             = 1055,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_LOGIN_GETSERVERLIST         = 1056,   //[TRANSLATED][TRANSLATED]serverlist[TRANSLATED][TRANSLATED]

    TYPE_CHANGE_MONEY                = 1108,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_ACTION               = 1109,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_HEROLEVEL            = 1210,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_HERONAME             = 1211,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_HEROHEAD             = 1212,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_HEROEXP              = 1213,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHANGE_FIGHTVALUE           = 1214,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_BAG_SORT_BAG                = 1301,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_USE_ITEM                = 1302,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_USE_BOX                 = 1303,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_DRESS_EQUIP             = 1304,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_UNLOAD_EQUIP            = 1305,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_DRESS_GEM               = 1306,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_UNLOAD_GEM              = 1307,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_COMPOSE_CHIP            = 1308,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_STRENGTHEN_EQUIP        = 1309,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_ADVANCE_EQUIP           = 1310,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED],
    TYPE_BAG_UPSTAR_EQUIP            = 1311,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_BAG_STRENGTHEN_GEM          = 1312,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_ECTYPE_PASSCOPY             = 1401,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ECTYPE_CHAPTERAWARD         = 1402,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ECTYPE_BATTLECHECK          = 1403,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_ACTOR_MOVE_JOYSTICK         = 1501,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ACTOR_STOP_JOYSTICK         = 1502,   //stop[TRANSLATED][TRANSLATED]
    TYPE_ACTOR_JUMP                  = 1503,   //[TRANSLATED][TRANSLATED]player[TRANSLATED][TRANSLATED]
    TYPE_ACTOR_CAST_SKILL            = 1504,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_ACTOR_MOVE_PURSUE           = 1505,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ACTOR_KILL_MONSTER          = 1506,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_ACTOR_AVATAR_DEAD           = 1507,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_UPDATE_AVATAR_HP            = 1601,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]life
    TYPE_UPDATE_AVATAR_MP            = 1602,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPDATE_AVATAR_SP            = 1603,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]SP
    TYPE_UPDATE_AVATAR_ATTR          = 1604,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPDATE_AVATAR_BUFF          = 1605,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]BUFF
    TYPE_UPDATE_PARTNER_HP           = 1606,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]life
    TYPE_UPDATE_BOSS_HP              = 1607,   //[TRANSLATED][TRANSLATED]BOSS[TRANSLATED][TRANSLATED]

    TYPE_MOUNT_STARTMOUNT            = 1801,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_MOUNT_LEAVEMOUNT            = 1802,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_MOUNT_DRESSMOUNT            = 1803,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_MOUNT_SELECTMOUNT           = 1804,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_RELICS_CHARGE               = 1901,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RELICS_UPGRADE              = 1902,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RELICS_BATTLE               = 1903,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RELICS_UNLOAD               = 1904,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_STORE_BUYSUCCESS            = 1905,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_PET_UPGRADE                 = 2001,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_PET_BATTLE                  = 2002,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_PET_UNLOAD                  = 2003,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_PARTNER_CHANGE              = 2004,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_PARTNER_ADVANCE             = 2005,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_PARTNER_UPGRADE             = 2006,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_SECOND_TICK                 = 2401,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_FORCE_STOPJOYSTICK          = 2402,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_TASK_STOP_AUTOTASK          = 2501,   //stop[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_TASK_SUBMIT_TASK            = 2502,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_TASK_THREAD_STATE           = 2601,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_TASK_BRANCH_STATE           = 2602,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_MAP_ENTERWORLD              = 2701,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_MOUSE_BUTTON                = 9001,
    TYPE_MOUSE_BUTTON_UP             = 9002,
    TYPE_MOUSE_BUTTON_DOWN           = 9003,
}