/* NOTE: original file backed up at /tmp/chinese_backups/Client___Assets___Scripts___GamePlay___TAS___Config___TaskDefine.cs */
﻿using UnityEngine;
using System.Collections;

namespace CFG
{
    public enum ETaskDialogAction
    {
        TYPE_NULL     = -1, 
        TYPE_NEXT     =  0,//[TRANSLATED][TRANSLATED][TRANSLATED]
        TYPE_LINK     =  1,//
        TYPE_COMPLETE =  2,//[TRANSLATED][TRANSLATED]
        TYPE_PASS     =  3,//[TRANSLATED][TRANSLATED]
    }

    public enum ETaskDialogPos
    {
        TYPE_NO  =-1,
        TYPE_LF  = 0,//[TRANSLATED]
        TYPE_RT  = 1 //[TRANSLATED]
    }

    public enum ETaskDialogRole
    {
        TYPE_PLAYER = 0,//player
        TYPE_NPC    = 1,//Npc
    }

    public enum ETaskDialogContent
    {
        TYPE_NORMAL,     //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
        TYPE_TYPEEFFECT, //TypeEffect
    }

    // [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]type
    public enum ETaskSubFuncType
    {
        TYPE_ERROR        =0, // errortype
        TYPE_TALK         =1, // [TRANSLATED][TRANSLATED]
        TYPE_HUNTER       =2, // [TRANSLATED][TRANSLATED]type
        TYPE_COLLECT      =3, // [TRANSLATED][TRANSLATED][TRANSLATED]
        TYPE_INTERACTIVE  =4, // [TRANSLATED][TRANSLATED]type
        TYPE_CONVOY       =5, // [TRANSLATED][TRANSLATED][TRANSLATED]
        TYPE_STORY        =6, // trigger[TRANSLATED][TRANSLATED]
        TYPE_CUTSCENE     =7, // trigger[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]	
        TYPE_USEITEM      =8, // [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]	
        TYPE_USESKILL     =9, // [TRANSLATED][TRANSLATED]skill
        TYPE_GATHER       =10,// [TRANSLATED][TRANSLATED]

    }

    //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    public enum ESubTaskState
    {
        TYPE_NONE,
        TYPE_INIT,
        TYPE_ENTER,
        TYPE_STEP,
        TYPE_EXIT,
        TYPE_STOP,
    }

    public enum ETaskNPCFlag
    {
        TYPE_NONE                 = 0,	// [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]handle([TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_CANSUBMIT            = 1,  // [TRANSLATED]can[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_CANSUBMIT_REPEAT     = 2,	// [TRANSLATED]can[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_NOT_COMPOLETE        = 3,	// [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_CAN_ACCEPT           = 4,	// can[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_CAN_ACCEPT_REPEAT    = 5,	// can[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_NOT_ACCEPT           = 6,	// [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]([TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED])
        TYPE_LOW_LEVEL            = 7,	// [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]Level[TRANSLATED][TRANSLATED]
        TYPE_INTERACTIVE          = 8,	// [TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    }

    public enum EConveyType
    {
        TYPE_AUTO,   //Npc[TRANSLATED][TRANSLATED][TRANSLATED]
        TYPE_FOLLOW, //[TRANSLATED][TRANSLATED]player
    }
}