/* NOTE: original file backed up at /tmp/chinese_backups/Client___Assets___Scripts___Defines___GTEnum.cs */
﻿using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;

public enum ELanguage
{
    Chinese,
    English
}

public enum EAction
{
    None   = 0,
    Manual = 1,
    Energy = 2,
}

public enum EPosType
{
    BagItem,
    BagGem,
    BagFashion,
    BagRune,
    BagChip,
    RoleEquip,
    RoleGem,
    RoleRune,
    RoleFashion,
    RoleMoney,
    RoleAction,
    Empty,
}

public enum EDataKeyType
{
    Id,
    Instance,
    Pos,
    Carrer,
}

public enum EMoney
{
    Gold    = 1,
    Diam    = 2,
    Crystal = 3,
    Glyph   = 4,
    Honor   = 5,
    Hoon    = 6,
    Fame    = 7,
    Mete    = 8,
    Apple   = 9,
    Soul    = 10,
    Goul    = 11,
    Poul    = 12
}

public enum EItemType
{
    EQUIP    = 1,
    DRUG     = 2,
    MAT      = 3,
    BOX      = 4,
    KEY      = 5,
    CHIP     = 6,
    GEM      = 7,
    FASHION  = 8,
    MONEY    = 9,
    ACTION   =10,
    EXP      =11,
    RUNE     =12,
    PETSOUL  =13,  
    TASK     =14,
}

public enum EBagType
{
    NONE    = 0,
    ITEM    = 1,
    GEM     = 2,
    FASHION = 3,
    CHIP    = 4,
    RUNE    = 5,
    TASK    = 6,
    SOUL    = 7,
    CARD    = 8  //Hero card
}

public enum ERuneType
{
    LIT = 1,//Small rune
    MID = 2,//Medium rune
    BIG = 3 //Large rune
}

public enum ECopyType
{
    TYPE_LOAD  = -1,
    TYPE_INIT  =  0,
    TYPE_LOGIN =  1,
    TYPE_ROLE  =  2,
    TYPE_CITY  =  3,
    TYPE_PVE   =  4,
    TYPE_WORLD =  5,
    TYPE_AREA  =  6,
}

public enum EStarCondition
{
    TYPE_PASSCOPY    = 0,
    TYPE_MAIN_HEALTH = 1,
    TYPE_TIME_LIMIT  = 2,
}

public enum ECompare
{
    EQ = 0,//Equal
    GT = 1,//Greater than
    LT = 2,//Less than
    GE = 3,//Greater than or equal
    LE = 4,//Less than or equal
    NO = 5,//Not equal
}

public enum EAffect
{
    Self = 1,//Affect self
    Enem = 2,//Affect enemy
    Ally = 3,//Affect ally
    Each = 4,//Affect all
    Boss = 5,//Affect Boss
    Host = 6,//Affect master
}

public enum EBattleCamp
{
    CT_NONE         = 0,
    CT_PVE_PLAYER   = 1,
    CT_PVE_ENEMY    = 2,
    CT_PVE_NEUTRAL  = 3,
    CT_PVP_PLAYER1  = 4,
    CT_PVP_PLAYER2  = 5,
    CT_PVP_PLAYER3  = 6,
    CT_PVP_PLAYER4  = 7,
    CT_PVP_PLAYER5  = 8,
}

public enum EDropType
{
    ONERAN = 1,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]count[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    MULFIX = 2,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    MULRAN = 3,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum ERecvType
{
    TYPE_RECV_ALL,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RECV_ONE,//[TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum ERewardState
{
    NOT_RECEIVE = 0,
    CAN_RECEIVE = 1,
    HAS_RECEIVE = 2,
}

public enum EDialoguePos
{
    LF = 0,
    RT = 1
}

public enum EDialogueContentShowType
{
    Normal = 0,
    Effect = 1
}

public enum EDialogueContentType
{
    TYPE_NONE   = 0,
    TYPE_PLAYER = 1,
    TYPE_ACTOR  = 2,
    TYPE_ITEM   = 3,
    TYPE_MAP    = 4
}

public enum ETaskType
{
    NONE,
    THREAD = 1,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    BRANCH = 2,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    DAILY  = 3,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum ETaskTargetType
{
    TYPE_NONE,
    TYPE_KILL_COPYBOSS  = 1,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]BOSS
    TYPE_MAIN_PASSCOPY  = 2,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]（[TRANSLATED][TRANSLATED]）
    TYPE_UPEQUIP        = 3,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPPET          = 4,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPGEM          = 5,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPPARTNER      = 6,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_UPSKILL        = 7,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_TALK           = 8,//[TRANSLATED][TRANSLATED]
    TYPE_ROB_TREASURE   = 9,//[TRANSLATED][TRANSLATED]
    TYPE_AREAE          = 10,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_PASS_ELITECOPY = 11,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_CHARGE_RELICE  = 12,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_EQUIPSTAR      = 13,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_XHJJC          = 14,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_KILLRACE       = 15,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}


public enum ETaskCycleType
{
    TYPE_NONE,
    TYPE_DAILY,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_WEEKLY,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SCENE,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum ETaskState
{
    QUEST_NONE,           //[TRANSLATED]type
    QUEST_DOING,          //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    QUEST_CANSUBMIT,      //[TRANSLATED][TRANSLATED][TRANSLATED]
    QUEST_FAILED,         //[TRANSLATED][TRANSLATED]Failure
    QUEST_HASSUBMIT,      //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum Resp : byte
{
    TYPE_YES                  = 0,  //Success
    TYPE_NO                   = 1,  //[TRANSLATED][TRANSLATED]
    TYPE_CANNOT_CONTROLSELF   = 2,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]，[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_CANNOT_MOVE          = 3,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] 
    TYPE_CANNOT_MOVETODEST    = 4,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]position 
    TYPE_HAS_DEAD             = 5,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    TYPE_SKILL_LACKHP         = 11,  //[TRANSLATED][TRANSLATED]HP
    TYPE_SKILL_LACKMP         = 12,  //[TRANSLATED][TRANSLATED]MP
    TYPE_SKILL_LACKSP         = 13,  //[TRANSLATED][TRANSLATED]SP
    TYPE_SKILL_CASTING        = 14,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_SKILL_LEADING        = 15,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_SKILL_CD             = 16,  //skill[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SKILL_NOTFIND        = 17,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_SKILL_NOTDOATSCENE   = 18,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]skill
    TYPE_SKILL_LACKXP         = 19,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_SKILL_SILENT         = 20,  //[TRANSLATED][TRANSLATED]

    TYPE_RIDE_ING             = 31,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RIDE_NOTDOATSCENE    = 32,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_RIDE_NOTDOATFSM      = 33,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED] 
    TYPE_RIDE_NONE            = 34,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]  
}

public enum EMoveType : byte
{
    SeekPosition,
    SeekTransform,
    SeekActor,
    MoveForce,
}

public enum FSMState : int
{
    FSM_EMPTY,
    FSM_BORN,                //[TRANSLATED][TRANSLATED]
    FSM_IDLE,                //[TRANSLATED][TRANSLATED]

    FSM_RUN,                 //[TRANSLATED][TRANSLATED]
    FSM_WALK,                //[TRANSLATED][TRANSLATED]

    FSM_SKILL,               //[TRANSLATED][TRANSLATED]
    FSM_DEAD,                //[TRANSLATED][TRANSLATED]
    FSM_REBORN,              //[TRANSLATED][TRANSLATED]

    FSM_WOUND,               //hit
    FSM_BEATBACK,            //[TRANSLATED][TRANSLATED]
    FSM_BEATDOWN,            //[TRANSLATED][TRANSLATED]
    FSM_BEATFLY,             //[TRANSLATED][TRANSLATED]
    FSM_FLOATING,            //[TRANSLATED][TRANSLATED]

    FSM_FROST,               //[TRANSLATED][TRANSLATED]
    FSM_STUN,                //[TRANSLATED][TRANSLATED]
    FSM_FIXBODY,             //[TRANSLATED][TRANSLATED]
    FSM_VARIATION,           //[TRANSLATED][TRANSLATED]
    FSM_FEAR,                //[TRANSLATED][TRANSLATED]
    FSM_SLEEP,               //[TRANSLATED][TRANSLATED]
    FSM_PARALY,              //[TRANSLATED][TRANSLATED]
    FSM_BLIND,               //[TRANSLATED][TRANSLATED]

    FSM_RIDEMOVE,            //[TRANSLATED][TRANSLATED][TRANSLATED]
    FSM_RIDEIDLE,            //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    FSM_RIDEATTACK,          //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    FSM_TALK,                //[TRANSLATED][TRANSLATED]
    FSM_HOOK,                //[TRANSLATED][TRANSLATED]
    FSM_GRAB,                //[TRANSLATED][TRANSLATED]
    FSM_FLY,                 //[TRANSLATED][TRANSLATED]
    FSM_ROLL,                //[TRANSLATED][TRANSLATED]
    FSM_JUMP,                //[TRANSLATED][TRANSLATED]

    FSM_DANCE,               //[TRANSLATED][TRANSLATED]
    FSM_MINE,                //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    FSM_INTERACTIVE,         //[TRANSLATED][TRANSLATED]
}

public enum EActorUnit
{
    Ground,//[TRANSLATED][TRANSLATED]
    Heaven //[TRANSLATED][TRANSLATED]
}

public enum EActorNature
{
    CAN_MOVE,          //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_KILL,          //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_MANUALATTACK,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_TURN,          //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_STUN,          //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_BEATBACK,      //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_BEATFLY,       //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_BEATDOWN,      //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_WOUND,         //[TRANSLATED]hit
    CAN_REDUCESPEED,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_FIXBODY,       //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_SLEEP,         //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_VARISTION,     //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_PARALY,        //[TRANSLATED][TRANSLATED][TRANSLATED]
    CAN_FEAR,          //[TRANSLATED][TRANSLATED][TRANSLATED]
}

public enum EActorType
{
    PLAYER  = 0,  //player
    NPC     = 1,  //NPC
    MONSTER = 2,  //[TRANSLATED][TRANSLATED]
    PET     = 3,  //[TRANSLATED][TRANSLATED]
    MOUNT   = 4,  //[TRANSLATED][TRANSLATED]
    MACHINE = 5,  //[TRANSLATED][TRANSLATED]
    PARTNER = 6,  //[TRANSLATED][TRANSLATED]
}

public enum EActorSex
{
    B,//[TRANSLATED]
    G,//[TRANSLATED]
    X,//[TRANSLATED][TRANSLATED]
}

//[TRANSLATED][TRANSLATED]type
public enum EActorSort
{
    None   = 0,
    Normal = 1,   //[TRANSLATED][TRANSLATED]
    Elite  = 2,   //[TRANSLATED][TRANSLATED]
    Rare   = 3,   //[TRANSLATED][TRANSLATED]
    Boss   = 4,   //Boss
    World  = 5,   //[TRANSLATED][TRANSLATED]Boss
    Chest  = 6,   //[TRANSLATED][TRANSLATED]
    Tower  = 7,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    Cage   = 8,   //[TRANSLATED][TRANSLATED]
}

//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
public enum EActorRace
{
    TYPE_NONE    = 1,    //[TRANSLATED][TRANSLATED]、[TRANSLATED][TRANSLATED][TRANSLATED]
    TYPE_HUMAN   = 2,    //[TRANSLATED][TRANSLATED]
    TYPE_SPIRIT  = 3,    //[TRANSLATED][TRANSLATED]
    TYPE_ORC     = 4,    //[TRANSLATED][TRANSLATED]
    TYPE_GHOST   = 5,    //[TRANSLATED][TRANSLATED]
    TYPE_DEVIL   = 6,    //[TRANSLATED][TRANSLATED]
    TYPE_ELEM    = 7,    //[TRANSLATED][TRANSLATED]
    TYPE_GIANT   = 8,    //[TRANSLATED][TRANSLATED]
    TYPE_MACHINE = 9,    //[TRANSLATED][TRANSLATED]
    TYPE_BEAST   = 10,   //[TRANSLATED][TRANSLATED]
    TYPE_DRAGON  = 11,   //[TRANSLATED][TRANSLATED]
}


public enum EAttr : int
{
    HP         = 1,   //life[TRANSLATED]
    AP         = 2,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    DF         = 3,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    CRIT       = 4,   //[TRANSLATED][TRANSLATED]
    CRITDAMAGE = 5,   //[TRANSLATED][TRANSLATED]
    MP         = 6,   //[TRANSLATED][TRANSLATED][TRANSLATED]
    SUCK       = 7,   //[TRANSLATED][TRANSLATED]
    HIT        = 8,   //[TRANSLATED][TRANSLATED]
    DODGE      = 9,   //[TRANSLATED][TRANSLATED]
    SP         = 10,  //[TRANSLATED][TRANSLATED][TRANSLATED]

    INJURY     = 11,  //[TRANSLATED][TRANSLATED]
    HPRECOVER  = 12,  //[TRANSLATED][TRANSLATED]
    MPRECOVER  = 13,  //[TRANSLATED][TRANSLATED]
    SPRECOVER  = 14,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    CRITDF     = 15,  //[TRANSLATED][TRANSLATED]
    SPEED      = 16,  //[TRANSLATED][TRANSLATED]

    PAP        = 17,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    PHP        = 18,  //life[TRANSLATED][TRANSLATED][TRANSLATED]
    PDF        = 19,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    PMP        = 20,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    EAP        = 21,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    EHP        = 22,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    EMP        = 23,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    ESP        = 24,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

    IAP        = 25,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    FAP        = 26,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    BAP        = 27,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    LAP        = 28,  //[TRANSLATED][TRANSLATED][TRANSLATED]

    IDF        = 29,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    FDF        = 30,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    BDF        = 31,  //[TRANSLATED][TRANSLATED][TRANSLATED]
    LDF        = 32,  //[TRANSLATED][TRANSLATED][TRANSLATED]

    MAXHP      = 33,  //[TRANSLATED][TRANSLATED]life[TRANSLATED] 
    MAXMP      = 34,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    MAXSP      = 35,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    ABSORB     = 36,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    REFLEX     = 37,  //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]

}

public enum ETargetRelationShip
{
    TYPE_NONE    =  0,
    TYPE_ALLY    =  1,
    TYPE_ENEMY   =  2,
    TYPE_NEUTRAL =  3,
}

public enum EPartnerSort
{
    LF           = 1,
    RT           = 2,
}

public enum EDeadReason
{
    Normal       = 0,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    Kill         = 1,   //[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
    Plot         = 2    //[TRANSLATED][TRANSLATED][TRANSLATED]
}


public enum ESyncDataType
{
    TYPE_ALL,
    TYPE_EQUIP,
    TYPE_BASEATTR,
    TYPE_CURRATTR,
    TYPE_AOI,
    TYPE_LEVEL,
    TYPE_NAME,
    TYPE_TITLE,
}

public enum EAIExecuteType
{
    TYPE_HANDLE     = 0,//[TRANSLATED][TRANSLATED]
    TYPE_AUTO       = 1,//[TRANSLATED][TRANSLATED]
    TYPE_AUTOPAUSED = 2,//[TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED][TRANSLATED]
}